# CMake generated Testfile for 
# Source directory: /home/koki/ros_catkin_ws/src/ros_comm/message_filters
# Build directory: /home/koki/ros_catkin_ws/build_isolated/message_filters
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_message_filters_gtest_message_filters-msg_cache_unittest "/home/koki/ros_catkin_ws/build_isolated/message_filters/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/gtest-message_filters-msg_cache_unittest.xml" "--return-code" "/home/koki/ros_catkin_ws/devel_isolated/message_filters/lib/message_filters/message_filters-msg_cache_unittest --gtest_output=xml:/home/koki/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/gtest-message_filters-msg_cache_unittest.xml")
set_tests_properties(_ctest_message_filters_gtest_message_filters-msg_cache_unittest PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/koki/ros_catkin_ws/src/ros_comm/message_filters/CMakeLists.txt;41;catkin_add_gtest;/home/koki/ros_catkin_ws/src/ros_comm/message_filters/CMakeLists.txt;0;")
add_test(_ctest_message_filters_gtest_message_filters-time_synchronizer_unittest "/home/koki/ros_catkin_ws/build_isolated/message_filters/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/gtest-message_filters-time_synchronizer_unittest.xml" "--return-code" "/home/koki/ros_catkin_ws/devel_isolated/message_filters/lib/message_filters/message_filters-time_synchronizer_unittest --gtest_output=xml:/home/koki/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/gtest-message_filters-time_synchronizer_unittest.xml")
set_tests_properties(_ctest_message_filters_gtest_message_filters-time_synchronizer_unittest PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/koki/ros_catkin_ws/src/ros_comm/message_filters/CMakeLists.txt;46;catkin_add_gtest;/home/koki/ros_catkin_ws/src/ros_comm/message_filters/CMakeLists.txt;0;")
add_test(_ctest_message_filters_gtest_message_filters-test_synchronizer "/home/koki/ros_catkin_ws/build_isolated/message_filters/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/gtest-message_filters-test_synchronizer.xml" "--return-code" "/home/koki/ros_catkin_ws/devel_isolated/message_filters/lib/message_filters/message_filters-test_synchronizer --gtest_output=xml:/home/koki/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/gtest-message_filters-test_synchronizer.xml")
set_tests_properties(_ctest_message_filters_gtest_message_filters-test_synchronizer PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/koki/ros_catkin_ws/src/ros_comm/message_filters/CMakeLists.txt;51;catkin_add_gtest;/home/koki/ros_catkin_ws/src/ros_comm/message_filters/CMakeLists.txt;0;")
add_test(_ctest_message_filters_gtest_message_filters-test_exact_time_policy "/home/koki/ros_catkin_ws/build_isolated/message_filters/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/gtest-message_filters-test_exact_time_policy.xml" "--return-code" "/home/koki/ros_catkin_ws/devel_isolated/message_filters/lib/message_filters/message_filters-test_exact_time_policy --gtest_output=xml:/home/koki/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/gtest-message_filters-test_exact_time_policy.xml")
set_tests_properties(_ctest_message_filters_gtest_message_filters-test_exact_time_policy PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/koki/ros_catkin_ws/src/ros_comm/message_filters/CMakeLists.txt;56;catkin_add_gtest;/home/koki/ros_catkin_ws/src/ros_comm/message_filters/CMakeLists.txt;0;")
add_test(_ctest_message_filters_gtest_message_filters-test_approximate_time_policy "/home/koki/ros_catkin_ws/build_isolated/message_filters/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/gtest-message_filters-test_approximate_time_policy.xml" "--return-code" "/home/koki/ros_catkin_ws/devel_isolated/message_filters/lib/message_filters/message_filters-test_approximate_time_policy --gtest_output=xml:/home/koki/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/gtest-message_filters-test_approximate_time_policy.xml")
set_tests_properties(_ctest_message_filters_gtest_message_filters-test_approximate_time_policy PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/koki/ros_catkin_ws/src/ros_comm/message_filters/CMakeLists.txt;61;catkin_add_gtest;/home/koki/ros_catkin_ws/src/ros_comm/message_filters/CMakeLists.txt;0;")
add_test(_ctest_message_filters_gtest_message_filters-test_simple "/home/koki/ros_catkin_ws/build_isolated/message_filters/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/gtest-message_filters-test_simple.xml" "--return-code" "/home/koki/ros_catkin_ws/devel_isolated/message_filters/lib/message_filters/message_filters-test_simple --gtest_output=xml:/home/koki/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/gtest-message_filters-test_simple.xml")
set_tests_properties(_ctest_message_filters_gtest_message_filters-test_simple PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/koki/ros_catkin_ws/src/ros_comm/message_filters/CMakeLists.txt;66;catkin_add_gtest;/home/koki/ros_catkin_ws/src/ros_comm/message_filters/CMakeLists.txt;0;")
add_test(_ctest_message_filters_gtest_message_filters-test_chain "/home/koki/ros_catkin_ws/build_isolated/message_filters/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/gtest-message_filters-test_chain.xml" "--return-code" "/home/koki/ros_catkin_ws/devel_isolated/message_filters/lib/message_filters/message_filters-test_chain --gtest_output=xml:/home/koki/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/gtest-message_filters-test_chain.xml")
set_tests_properties(_ctest_message_filters_gtest_message_filters-test_chain PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/koki/ros_catkin_ws/src/ros_comm/message_filters/CMakeLists.txt;71;catkin_add_gtest;/home/koki/ros_catkin_ws/src/ros_comm/message_filters/CMakeLists.txt;0;")
add_test(_ctest_message_filters_rostest_test_time_sequencer_unittest.xml "/home/koki/ros_catkin_ws/build_isolated/message_filters/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/rostest-test_time_sequencer_unittest.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/ros_comm/message_filters --package=message_filters --results-filename test_time_sequencer_unittest.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/message_filters/test_results\" /home/koki/ros_catkin_ws/src/ros_comm/message_filters/test/time_sequencer_unittest.xml ")
set_tests_properties(_ctest_message_filters_rostest_test_time_sequencer_unittest.xml PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;80;add_rostest;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;100;_add_rostest_google_test;/home/koki/ros_catkin_ws/src/ros_comm/message_filters/CMakeLists.txt;77;add_rostest_gtest;/home/koki/ros_catkin_ws/src/ros_comm/message_filters/CMakeLists.txt;0;")
add_test(_ctest_message_filters_rostest_test_test_subscriber.xml "/home/koki/ros_catkin_ws/build_isolated/message_filters/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/rostest-test_test_subscriber.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/ros_comm/message_filters --package=message_filters --results-filename test_test_subscriber.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/message_filters/test_results\" /home/koki/ros_catkin_ws/src/ros_comm/message_filters/test/test_subscriber.xml ")
set_tests_properties(_ctest_message_filters_rostest_test_test_subscriber.xml PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;80;add_rostest;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;100;_add_rostest_google_test;/home/koki/ros_catkin_ws/src/ros_comm/message_filters/CMakeLists.txt;82;add_rostest_gtest;/home/koki/ros_catkin_ws/src/ros_comm/message_filters/CMakeLists.txt;0;")
add_test(_ctest_message_filters_nosetests_test.test_approxsync.py "/home/koki/ros_catkin_ws/build_isolated/message_filters/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/nosetests-test.test_approxsync.py.xml" "--return-code" "\"/home/koki/.local/lib/python3.6/site-packages/cmake/data/bin/cmake\" -E make_directory /home/koki/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters" "/usr/bin/nosetests3 -P --process-timeout=60 /home/koki/ros_catkin_ws/src/ros_comm/message_filters/test/test_approxsync.py --with-xunit --xunit-file=/home/koki/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/nosetests-test.test_approxsync.py.xml")
set_tests_properties(_ctest_message_filters_nosetests_test.test_approxsync.py PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/nosetests.cmake;83;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/ros_comm/message_filters/CMakeLists.txt;88;catkin_add_nosetests;/home/koki/ros_catkin_ws/src/ros_comm/message_filters/CMakeLists.txt;0;")
add_test(_ctest_message_filters_nosetests_test.test_message_filters_cache.py "/home/koki/ros_catkin_ws/build_isolated/message_filters/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/nosetests-test.test_message_filters_cache.py.xml" "--return-code" "\"/home/koki/.local/lib/python3.6/site-packages/cmake/data/bin/cmake\" -E make_directory /home/koki/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters" "/usr/bin/nosetests3 -P --process-timeout=60 /home/koki/ros_catkin_ws/src/ros_comm/message_filters/test/test_message_filters_cache.py --with-xunit --xunit-file=/home/koki/ros_catkin_ws/build_isolated/message_filters/test_results/message_filters/nosetests-test.test_message_filters_cache.py.xml")
set_tests_properties(_ctest_message_filters_nosetests_test.test_message_filters_cache.py PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/nosetests.cmake;83;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/ros_comm/message_filters/CMakeLists.txt;89;catkin_add_nosetests;/home/koki/ros_catkin_ws/src/ros_comm/message_filters/CMakeLists.txt;0;")
subdirs("gtest")
