# CMake generated Testfile for 
# Source directory: /home/koki/ros_catkin_ws/src/rosbridge_suite/rosbridge_library
# Build directory: /home/koki/ros_catkin_ws/build_isolated/rosbridge_library
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_rosbridge_library_rostest_test_capabilities_test_capabilities.test "/home/koki/ros_catkin_ws/build_isolated/rosbridge_library/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/rosbridge_library/test_results/rosbridge_library/rostest-test_capabilities_test_capabilities.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/rosbridge_suite/rosbridge_library --package=rosbridge_library --results-filename test_capabilities_test_capabilities.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/rosbridge_library/test_results\" /home/koki/ros_catkin_ws/src/rosbridge_suite/rosbridge_library/test/capabilities/test_capabilities.test ")
set_tests_properties(_ctest_rosbridge_library_rostest_test_capabilities_test_capabilities.test PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/rosbridge_suite/rosbridge_library/CMakeLists.txt;53;add_rostest;/home/koki/ros_catkin_ws/src/rosbridge_suite/rosbridge_library/CMakeLists.txt;0;")
add_test(_ctest_rosbridge_library_rostest_test_internal_test_internal.test "/home/koki/ros_catkin_ws/build_isolated/rosbridge_library/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/rosbridge_library/test_results/rosbridge_library/rostest-test_internal_test_internal.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/rosbridge_suite/rosbridge_library --package=rosbridge_library --results-filename test_internal_test_internal.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/rosbridge_library/test_results\" /home/koki/ros_catkin_ws/src/rosbridge_suite/rosbridge_library/test/internal/test_internal.test ")
set_tests_properties(_ctest_rosbridge_library_rostest_test_internal_test_internal.test PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/rosbridge_suite/rosbridge_library/CMakeLists.txt;54;add_rostest;/home/koki/ros_catkin_ws/src/rosbridge_suite/rosbridge_library/CMakeLists.txt;0;")
subdirs("gtest")
