set(joint_state_publisher_SETUP_PY_SETUP_MODULE "distutils.core")
set(joint_state_publisher_SETUP_PY_VERSION "1.12.15")
set(joint_state_publisher_SETUP_PY_SCRIPTS "")
set(joint_state_publisher_SETUP_PY_PACKAGES "joint_state_publisher")
set(joint_state_publisher_SETUP_PY_PACKAGE_DIRS "src/joint_state_publisher")
set(joint_state_publisher_SETUP_PY_MODULES "")
set(joint_state_publisher_SETUP_PY_MODULE_DIRS "")