# CMake generated Testfile for 
# Source directory: /home/koki/ros_catkin_ws/src/vision_opencv/image_geometry/test
# Build directory: /home/koki/ros_catkin_ws/build_isolated/image_geometry/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_image_geometry_nosetests_directed.py "/home/koki/ros_catkin_ws/build_isolated/image_geometry/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/image_geometry/test_results/image_geometry/nosetests-directed.py.xml" "--return-code" "\"/home/koki/.local/lib/python3.6/site-packages/cmake/data/bin/cmake\" -E make_directory /home/koki/ros_catkin_ws/build_isolated/image_geometry/test_results/image_geometry" "/usr/bin/nosetests3 -P --process-timeout=60 /home/koki/ros_catkin_ws/src/vision_opencv/image_geometry/test/directed.py --with-xunit --xunit-file=/home/koki/ros_catkin_ws/build_isolated/image_geometry/test_results/image_geometry/nosetests-directed.py.xml")
set_tests_properties(_ctest_image_geometry_nosetests_directed.py PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/nosetests.cmake;83;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/vision_opencv/image_geometry/test/CMakeLists.txt;1;catkin_add_nosetests;/home/koki/ros_catkin_ws/src/vision_opencv/image_geometry/test/CMakeLists.txt;0;")
add_test(_ctest_image_geometry_gtest_image_geometry-utest "/home/koki/ros_catkin_ws/build_isolated/image_geometry/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/image_geometry/test_results/image_geometry/gtest-image_geometry-utest.xml" "--return-code" "/home/koki/ros_catkin_ws/devel_isolated/image_geometry/lib/image_geometry/image_geometry-utest --gtest_output=xml:/home/koki/ros_catkin_ws/build_isolated/image_geometry/test_results/image_geometry/gtest-image_geometry-utest.xml")
set_tests_properties(_ctest_image_geometry_gtest_image_geometry-utest PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/koki/ros_catkin_ws/src/vision_opencv/image_geometry/test/CMakeLists.txt;3;catkin_add_gtest;/home/koki/ros_catkin_ws/src/vision_opencv/image_geometry/test/CMakeLists.txt;0;")
