# CMake generated Testfile for 
# Source directory: /home/koki/ros_catkin_ws/src/stage_ros
# Build directory: /home/koki/ros_catkin_ws/build_isolated/stage_ros
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_stage_ros_rostest_test_hztest.xml "/home/koki/ros_catkin_ws/build_isolated/stage_ros/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/stage_ros/test_results/stage_ros/rostest-test_hztest.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/stage_ros --package=stage_ros --results-filename test_hztest.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/stage_ros/test_results\" /home/koki/ros_catkin_ws/src/stage_ros/test/hztest.xml ")
set_tests_properties(_ctest_stage_ros_rostest_test_hztest.xml PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/stage_ros/CMakeLists.txt;64;add_rostest;/home/koki/ros_catkin_ws/src/stage_ros/CMakeLists.txt;0;")
add_test(_ctest_stage_ros_rostest_test_intensity_test.xml "/home/koki/ros_catkin_ws/build_isolated/stage_ros/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/stage_ros/test_results/stage_ros/rostest-test_intensity_test.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/stage_ros --package=stage_ros --results-filename test_intensity_test.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/stage_ros/test_results\" /home/koki/ros_catkin_ws/src/stage_ros/test/intensity_test.xml ")
set_tests_properties(_ctest_stage_ros_rostest_test_intensity_test.xml PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/stage_ros/CMakeLists.txt;65;add_rostest;/home/koki/ros_catkin_ws/src/stage_ros/CMakeLists.txt;0;")
subdirs("gtest")
