# CMake generated Testfile for 
# Source directory: /home/koki/ros_catkin_ws/src/rosconsole
# Build directory: /home/koki/ros_catkin_ws/build_isolated/rosconsole
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_rosconsole_gtest_rosconsole-utest "/home/koki/ros_catkin_ws/build_isolated/rosconsole/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/rosconsole/test_results/rosconsole/gtest-rosconsole-utest.xml" "--return-code" "/home/koki/ros_catkin_ws/devel_isolated/rosconsole/lib/rosconsole/rosconsole-utest --gtest_output=xml:/home/koki/ros_catkin_ws/build_isolated/rosconsole/test_results/rosconsole/gtest-rosconsole-utest.xml")
set_tests_properties(_ctest_rosconsole_gtest_rosconsole-utest PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/koki/ros_catkin_ws/src/rosconsole/CMakeLists.txt;111;catkin_add_gtest;/home/koki/ros_catkin_ws/src/rosconsole/CMakeLists.txt;0;")
add_test(_ctest_rosconsole_gtest_rosconsole-assertion_test "/home/koki/ros_catkin_ws/build_isolated/rosconsole/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/rosconsole/test_results/rosconsole/gtest-rosconsole-assertion_test.xml" "--return-code" "/home/koki/ros_catkin_ws/devel_isolated/rosconsole/lib/rosconsole/rosconsole-assertion_test --gtest_output=xml:/home/koki/ros_catkin_ws/build_isolated/rosconsole/test_results/rosconsole/gtest-rosconsole-assertion_test.xml")
set_tests_properties(_ctest_rosconsole_gtest_rosconsole-assertion_test PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/koki/ros_catkin_ws/src/rosconsole/CMakeLists.txt;117;catkin_add_gtest;/home/koki/ros_catkin_ws/src/rosconsole/CMakeLists.txt;0;")
add_test(_ctest_rosconsole_gtest_rosconsole-thread_test "/home/koki/ros_catkin_ws/build_isolated/rosconsole/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/rosconsole/test_results/rosconsole/gtest-rosconsole-thread_test.xml" "--return-code" "/home/koki/ros_catkin_ws/devel_isolated/rosconsole/lib/rosconsole/rosconsole-thread_test --gtest_output=xml:/home/koki/ros_catkin_ws/build_isolated/rosconsole/test_results/rosconsole/gtest-rosconsole-thread_test.xml")
set_tests_properties(_ctest_rosconsole_gtest_rosconsole-thread_test PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/koki/ros_catkin_ws/src/rosconsole/CMakeLists.txt;123;catkin_add_gtest;/home/koki/ros_catkin_ws/src/rosconsole/CMakeLists.txt;0;")
subdirs("gtest")
