# CMake generated Testfile for 
# Source directory: /home/koki/ros_catkin_ws/src/ros/roslib
# Build directory: /home/koki/ros_catkin_ws/build_isolated/roslib
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_roslib_nosetests_test "/home/koki/ros_catkin_ws/build_isolated/roslib/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/roslib/test_results/roslib/nosetests-test.xml" "--return-code" "\"/home/koki/.local/lib/python3.6/site-packages/cmake/data/bin/cmake\" -E make_directory /home/koki/ros_catkin_ws/build_isolated/roslib/test_results/roslib" "/usr/bin/nosetests3 -P --process-timeout=60 --where=/home/koki/ros_catkin_ws/src/ros/roslib/test --with-xunit --xunit-file=/home/koki/ros_catkin_ws/build_isolated/roslib/test_results/roslib/nosetests-test.xml")
set_tests_properties(_ctest_roslib_nosetests_test PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/nosetests.cmake;83;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/ros/roslib/CMakeLists.txt;42;catkin_add_nosetests;/home/koki/ros_catkin_ws/src/ros/roslib/CMakeLists.txt;0;")
add_test(_ctest_roslib_gtest_roslib-utest "/home/koki/ros_catkin_ws/build_isolated/roslib/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/roslib/test_results/roslib/gtest-roslib-utest.xml" "--working-dir" "/home/koki/ros_catkin_ws/src/ros/roslib" "--return-code" "/home/koki/ros_catkin_ws/devel_isolated/roslib/lib/roslib/roslib-utest --gtest_output=xml:/home/koki/ros_catkin_ws/build_isolated/roslib/test_results/roslib/gtest-roslib-utest.xml")
set_tests_properties(_ctest_roslib_gtest_roslib-utest PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/koki/ros_catkin_ws/src/ros/roslib/CMakeLists.txt;44;catkin_add_gtest;/home/koki/ros_catkin_ws/src/ros/roslib/CMakeLists.txt;0;")
add_test(_ctest_roslib_gtest_roslib-test_package "/home/koki/ros_catkin_ws/build_isolated/roslib/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/roslib/test_results/roslib/gtest-roslib-test_package.xml" "--return-code" "/home/koki/ros_catkin_ws/devel_isolated/roslib/lib/roslib/roslib-test_package --gtest_output=xml:/home/koki/ros_catkin_ws/build_isolated/roslib/test_results/roslib/gtest-roslib-test_package.xml")
set_tests_properties(_ctest_roslib_gtest_roslib-test_package PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/koki/ros_catkin_ws/src/ros/roslib/CMakeLists.txt;49;catkin_add_gtest;/home/koki/ros_catkin_ws/src/ros/roslib/CMakeLists.txt;0;")
subdirs("gtest")
