# CMake generated Testfile for 
# Source directory: /home/koki/ros_catkin_ws/src/urdf/urdf
# Build directory: /home/koki/ros_catkin_ws/build_isolated/urdf
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_urdf_rostest_test_test_robot_model_parser.launch "/home/koki/ros_catkin_ws/build_isolated/urdf/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/urdf/test_results/urdf/rostest-test_test_robot_model_parser.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/urdf/urdf --package=urdf --results-filename test_test_robot_model_parser.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/urdf/test_results\" /home/koki/ros_catkin_ws/src/urdf/urdf/test/test_robot_model_parser.launch ")
set_tests_properties(_ctest_urdf_rostest_test_test_robot_model_parser.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;80;add_rostest;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;100;_add_rostest_google_test;/home/koki/ros_catkin_ws/src/urdf/urdf/CMakeLists.txt;61;add_rostest_gtest;/home/koki/ros_catkin_ws/src/urdf/urdf/CMakeLists.txt;0;")
add_test(_ctest_urdf_gtest_urdfdom_compatibility_test "/home/koki/ros_catkin_ws/build_isolated/urdf/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/urdf/test_results/urdf/gtest-urdfdom_compatibility_test.xml" "--return-code" "/home/koki/ros_catkin_ws/devel_isolated/urdf/lib/urdf/urdfdom_compatibility_test --gtest_output=xml:/home/koki/ros_catkin_ws/build_isolated/urdf/test_results/urdf/gtest-urdfdom_compatibility_test.xml")
set_tests_properties(_ctest_urdf_gtest_urdfdom_compatibility_test PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/koki/ros_catkin_ws/src/urdf/urdf/CMakeLists.txt;64;catkin_add_gtest;/home/koki/ros_catkin_ws/src/urdf/urdf/CMakeLists.txt;0;")
add_test(_ctest_urdf_gtest_test_model_parser_initxml "/home/koki/ros_catkin_ws/build_isolated/urdf/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/urdf/test_results/urdf/gtest-test_model_parser_initxml.xml" "--return-code" "/home/koki/ros_catkin_ws/devel_isolated/urdf/lib/urdf/test_model_parser_initxml --gtest_output=xml:/home/koki/ros_catkin_ws/build_isolated/urdf/test_results/urdf/gtest-test_model_parser_initxml.xml")
set_tests_properties(_ctest_urdf_gtest_test_model_parser_initxml PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/koki/ros_catkin_ws/src/urdf/urdf/CMakeLists.txt;70;catkin_add_gtest;/home/koki/ros_catkin_ws/src/urdf/urdf/CMakeLists.txt;0;")
subdirs("gtest")
