# CMake generated Testfile for 
# Source directory: /home/koki/ros_catkin_ws/src/ros_comm/rostest
# Build directory: /home/koki/ros_catkin_ws/build_isolated/rostest
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_rostest_gtest_test_permuter "/home/koki/ros_catkin_ws/build_isolated/rostest/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/rostest/test_results/rostest/gtest-test_permuter.xml" "--return-code" "/home/koki/ros_catkin_ws/devel_isolated/rostest/lib/rostest/test_permuter --gtest_output=xml:/home/koki/ros_catkin_ws/build_isolated/rostest/test_results/rostest/gtest-test_permuter.xml")
set_tests_properties(_ctest_rostest_gtest_test_permuter PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/koki/ros_catkin_ws/src/ros_comm/rostest/CMakeLists.txt;25;catkin_add_gtest;/home/koki/ros_catkin_ws/src/ros_comm/rostest/CMakeLists.txt;0;")
add_test(_ctest_rostest_rostest_test_hztest0.test "/home/koki/ros_catkin_ws/build_isolated/rostest/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/rostest/test_results/rostest/rostest-test_hztest0.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/src/ros_comm/rostest/scripts/rostest --pkgdir=/home/koki/ros_catkin_ws/src/ros_comm/rostest --package=rostest --results-filename test_hztest0.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/rostest/test_results\" /home/koki/ros_catkin_ws/src/ros_comm/rostest/test/hztest0.test ")
set_tests_properties(_ctest_rostest_rostest_test_hztest0.test PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/devel_isolated/rostest/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/ros_comm/rostest/CMakeLists.txt;30;add_rostest;/home/koki/ros_catkin_ws/src/ros_comm/rostest/CMakeLists.txt;0;")
add_test(_ctest_rostest_rostest_test_hztest.test "/home/koki/ros_catkin_ws/build_isolated/rostest/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/rostest/test_results/rostest/rostest-test_hztest.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/src/ros_comm/rostest/scripts/rostest --pkgdir=/home/koki/ros_catkin_ws/src/ros_comm/rostest --package=rostest --results-filename test_hztest.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/rostest/test_results\" /home/koki/ros_catkin_ws/src/ros_comm/rostest/test/hztest.test ")
set_tests_properties(_ctest_rostest_rostest_test_hztest.test PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/devel_isolated/rostest/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/ros_comm/rostest/CMakeLists.txt;31;add_rostest;/home/koki/ros_catkin_ws/src/ros_comm/rostest/CMakeLists.txt;0;")
add_test(_ctest_rostest_rostest_test_publishtest.test "/home/koki/ros_catkin_ws/build_isolated/rostest/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/rostest/test_results/rostest/rostest-test_publishtest.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/src/ros_comm/rostest/scripts/rostest --pkgdir=/home/koki/ros_catkin_ws/src/ros_comm/rostest --package=rostest --results-filename test_publishtest.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/rostest/test_results\" /home/koki/ros_catkin_ws/src/ros_comm/rostest/test/publishtest.test ")
set_tests_properties(_ctest_rostest_rostest_test_publishtest.test PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/devel_isolated/rostest/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/ros_comm/rostest/CMakeLists.txt;32;add_rostest;/home/koki/ros_catkin_ws/src/ros_comm/rostest/CMakeLists.txt;0;")
add_test(_ctest_rostest_rostest_test_clean_master.test "/home/koki/ros_catkin_ws/build_isolated/rostest/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/rostest/test_results/rostest/rostest-test_clean_master.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/src/ros_comm/rostest/scripts/rostest --pkgdir=/home/koki/ros_catkin_ws/src/ros_comm/rostest --package=rostest --results-filename test_clean_master.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/rostest/test_results\" /home/koki/ros_catkin_ws/src/ros_comm/rostest/test/clean_master.test ")
set_tests_properties(_ctest_rostest_rostest_test_clean_master.test PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/devel_isolated/rostest/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/ros_comm/rostest/CMakeLists.txt;33;add_rostest;/home/koki/ros_catkin_ws/src/ros_comm/rostest/CMakeLists.txt;0;")
add_test(_ctest_rostest_rostest_test_distro_version.test "/home/koki/ros_catkin_ws/build_isolated/rostest/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/rostest/test_results/rostest/rostest-test_distro_version.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/src/ros_comm/rostest/scripts/rostest --pkgdir=/home/koki/ros_catkin_ws/src/ros_comm/rostest --package=rostest --results-filename test_distro_version.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/rostest/test_results\" /home/koki/ros_catkin_ws/src/ros_comm/rostest/test/distro_version.test ")
set_tests_properties(_ctest_rostest_rostest_test_distro_version.test PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/devel_isolated/rostest/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/ros_comm/rostest/CMakeLists.txt;34;add_rostest;/home/koki/ros_catkin_ws/src/ros_comm/rostest/CMakeLists.txt;0;")
add_test(_ctest_rostest_rostest_test_param.test "/home/koki/ros_catkin_ws/build_isolated/rostest/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/rostest/test_results/rostest/rostest-test_param.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/src/ros_comm/rostest/scripts/rostest --pkgdir=/home/koki/ros_catkin_ws/src/ros_comm/rostest --package=rostest --results-filename test_param.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/rostest/test_results\" /home/koki/ros_catkin_ws/src/ros_comm/rostest/test/param.test ")
set_tests_properties(_ctest_rostest_rostest_test_param.test PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/devel_isolated/rostest/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/ros_comm/rostest/CMakeLists.txt;35;add_rostest;/home/koki/ros_catkin_ws/src/ros_comm/rostest/CMakeLists.txt;0;")
add_test(_ctest_rostest_rostest_test_advertisetest.test "/home/koki/ros_catkin_ws/build_isolated/rostest/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/rostest/test_results/rostest/rostest-test_advertisetest.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/src/ros_comm/rostest/scripts/rostest --pkgdir=/home/koki/ros_catkin_ws/src/ros_comm/rostest --package=rostest --results-filename test_advertisetest.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/rostest/test_results\" /home/koki/ros_catkin_ws/src/ros_comm/rostest/test/advertisetest.test ")
set_tests_properties(_ctest_rostest_rostest_test_advertisetest.test PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/devel_isolated/rostest/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/ros_comm/rostest/CMakeLists.txt;36;add_rostest;/home/koki/ros_catkin_ws/src/ros_comm/rostest/CMakeLists.txt;0;")
subdirs("gtest")
