set(diagnostic_analysis_SETUP_PY_SETUP_MODULE "distutils.core")
set(diagnostic_analysis_SETUP_PY_VERSION "1.9.7")
set(diagnostic_analysis_SETUP_PY_SCRIPTS "")
set(diagnostic_analysis_SETUP_PY_PACKAGES "diagnostic_analysis")
set(diagnostic_analysis_SETUP_PY_PACKAGE_DIRS "src/diagnostic_analysis")
set(diagnostic_analysis_SETUP_PY_MODULES "")
set(diagnostic_analysis_SETUP_PY_MODULE_DIRS "")