# CMake generated Testfile for 
# Source directory: /home/koki/ros_catkin_ws/src/robot_state_publisher
# Build directory: /home/koki/ros_catkin_ws/build_isolated/robot_state_publisher
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_robot_state_publisher_rostest_test_test_one_link.launch "/home/koki/ros_catkin_ws/build_isolated/robot_state_publisher/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/robot_state_publisher/test_results/robot_state_publisher/rostest-test_test_one_link.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/robot_state_publisher --package=robot_state_publisher --results-filename test_test_one_link.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/robot_state_publisher/test_results\" /home/koki/ros_catkin_ws/src/robot_state_publisher/test/test_one_link.launch ")
set_tests_properties(_ctest_robot_state_publisher_rostest_test_test_one_link.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;80;add_rostest;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;100;_add_rostest_google_test;/home/koki/ros_catkin_ws/src/robot_state_publisher/CMakeLists.txt;64;add_rostest_gtest;/home/koki/ros_catkin_ws/src/robot_state_publisher/CMakeLists.txt;0;")
add_test(_ctest_robot_state_publisher_rostest_test_test_two_links_fixed_joint.launch "/home/koki/ros_catkin_ws/build_isolated/robot_state_publisher/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/robot_state_publisher/test_results/robot_state_publisher/rostest-test_test_two_links_fixed_joint.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/robot_state_publisher --package=robot_state_publisher --results-filename test_test_two_links_fixed_joint.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/robot_state_publisher/test_results\" /home/koki/ros_catkin_ws/src/robot_state_publisher/test/test_two_links_fixed_joint.launch ")
set_tests_properties(_ctest_robot_state_publisher_rostest_test_test_two_links_fixed_joint.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;80;add_rostest;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;100;_add_rostest_google_test;/home/koki/ros_catkin_ws/src/robot_state_publisher/CMakeLists.txt;67;add_rostest_gtest;/home/koki/ros_catkin_ws/src/robot_state_publisher/CMakeLists.txt;0;")
add_test(_ctest_robot_state_publisher_rostest_test_test_two_links_moving_joint.launch "/home/koki/ros_catkin_ws/build_isolated/robot_state_publisher/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/robot_state_publisher/test_results/robot_state_publisher/rostest-test_test_two_links_moving_joint.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/robot_state_publisher --package=robot_state_publisher --results-filename test_test_two_links_moving_joint.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/robot_state_publisher/test_results\" /home/koki/ros_catkin_ws/src/robot_state_publisher/test/test_two_links_moving_joint.launch ")
set_tests_properties(_ctest_robot_state_publisher_rostest_test_test_two_links_moving_joint.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;80;add_rostest;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;100;_add_rostest_google_test;/home/koki/ros_catkin_ws/src/robot_state_publisher/CMakeLists.txt;70;add_rostest_gtest;/home/koki/ros_catkin_ws/src/robot_state_publisher/CMakeLists.txt;0;")
add_test(_ctest_robot_state_publisher_rostest_test_test_joint_states_bag.launch "/home/koki/ros_catkin_ws/build_isolated/robot_state_publisher/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/robot_state_publisher/test_results/robot_state_publisher/rostest-test_test_joint_states_bag.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/robot_state_publisher --package=robot_state_publisher --results-filename test_test_joint_states_bag.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/robot_state_publisher/test_results\" /home/koki/ros_catkin_ws/src/robot_state_publisher/test/test_joint_states_bag.launch ")
set_tests_properties(_ctest_robot_state_publisher_rostest_test_test_joint_states_bag.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;80;add_rostest;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;100;_add_rostest_google_test;/home/koki/ros_catkin_ws/src/robot_state_publisher/CMakeLists.txt;81;add_rostest_gtest;/home/koki/ros_catkin_ws/src/robot_state_publisher/CMakeLists.txt;0;")
add_test(_ctest_robot_state_publisher_rostest_test_test_subclass.launch "/home/koki/ros_catkin_ws/build_isolated/robot_state_publisher/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/robot_state_publisher/test_results/robot_state_publisher/rostest-test_test_subclass.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/robot_state_publisher --package=robot_state_publisher --results-filename test_test_subclass.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/robot_state_publisher/test_results\" /home/koki/ros_catkin_ws/src/robot_state_publisher/test/test_subclass.launch ")
set_tests_properties(_ctest_robot_state_publisher_rostest_test_test_subclass.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;80;add_rostest;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;100;_add_rostest_google_test;/home/koki/ros_catkin_ws/src/robot_state_publisher/CMakeLists.txt;84;add_rostest_gtest;/home/koki/ros_catkin_ws/src/robot_state_publisher/CMakeLists.txt;0;")
subdirs("gtest")
