# CMake generated Testfile for 
# Source directory: /home/koki/ros_catkin_ws/src/nodelet_core/test_nodelet_topic_tools
# Build directory: /home/koki/ros_catkin_ws/build_isolated/test_nodelet_topic_tools
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_test_nodelet_topic_tools_rostest_test_test_nodelet_lazy.launch "/home/koki/ros_catkin_ws/build_isolated/test_nodelet_topic_tools/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/test_nodelet_topic_tools/test_results/test_nodelet_topic_tools/rostest-test_test_nodelet_lazy.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/nodelet_core/test_nodelet_topic_tools --package=test_nodelet_topic_tools --results-filename test_test_nodelet_lazy.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/test_nodelet_topic_tools/test_results\" /home/koki/ros_catkin_ws/src/nodelet_core/test_nodelet_topic_tools/test/test_nodelet_lazy.launch ")
set_tests_properties(_ctest_test_nodelet_topic_tools_rostest_test_test_nodelet_lazy.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/nodelet_core/test_nodelet_topic_tools/CMakeLists.txt;17;add_rostest;/home/koki/ros_catkin_ws/src/nodelet_core/test_nodelet_topic_tools/CMakeLists.txt;0;")
add_test(_ctest_test_nodelet_topic_tools_rostest_test_test_nodelet_throttle.launch "/home/koki/ros_catkin_ws/build_isolated/test_nodelet_topic_tools/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/test_nodelet_topic_tools/test_results/test_nodelet_topic_tools/rostest-test_test_nodelet_throttle.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/nodelet_core/test_nodelet_topic_tools --package=test_nodelet_topic_tools --results-filename test_test_nodelet_throttle.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/test_nodelet_topic_tools/test_results\" /home/koki/ros_catkin_ws/src/nodelet_core/test_nodelet_topic_tools/test/test_nodelet_throttle.launch ")
set_tests_properties(_ctest_test_nodelet_topic_tools_rostest_test_test_nodelet_throttle.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/nodelet_core/test_nodelet_topic_tools/CMakeLists.txt;18;add_rostest;/home/koki/ros_catkin_ws/src/nodelet_core/test_nodelet_topic_tools/CMakeLists.txt;0;")
subdirs("gtest")
