#!/bin/sh
rosservice call /drone01/enable_motors false
rosservice call /drone02/enable_motors false
rosservice call /drone03/enable_motors false
rosservice call /drone04/enable_motors false
rosservice call /drone05/enable_motors false
rosservice call /drone06/enable_motors false
rosservice call /drone07/enable_motors false
rosservice call /drone08/enable_motors false
rosservice call /drone09/enable_motors false
rosservice call /drone10/enable_motors false
rosservice call /drone11/enable_motors false
rosservice call /drone12/enable_motors false
rosservice call /drone13/enable_motors false
rosservice call /drone14/enable_motors false
rosservice call /drone15/enable_motors false
rosservice call /drone16/enable_motors false
rosservice call /drone17/enable_motors false
rosservice call /drone18/enable_motors false
rosservice call /drone19/enable_motors false
rosservice call /drone20/enable_motors false
rosservice call /drone21/enable_motors false
rosservice call /drone22/enable_motors false
rosservice call /drone23/enable_motors false
rosservice call /drone24/enable_motors false
rosservice call /drone25/enable_motors false
rosservice call /drone26/enable_motors false
rosservice call /drone27/enable_motors false
rosservice call /drone28/enable_motors false
rosservice call /drone29/enable_motors false
rosservice call /drone30/enable_motors false
rosservice call /drone31/enable_motors false
rosservice call /drone32/enable_motors false
rosservice call /drone33/enable_motors false
rosservice call /drone34/enable_motors false
rosservice call /drone35/enable_motors false
rosservice call /drone36/enable_motors false
rosservice call /drone37/enable_motors false