# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/home/koki/ros_catkin_ws/src/geographic_info/geographic_msgs/msg/BoundingBox.msg;/home/koki/ros_catkin_ws/src/geographic_info/geographic_msgs/msg/GeographicMapChanges.msg;/home/koki/ros_catkin_ws/src/geographic_info/geographic_msgs/msg/GeographicMap.msg;/home/koki/ros_catkin_ws/src/geographic_info/geographic_msgs/msg/GeoPath.msg;/home/koki/ros_catkin_ws/src/geographic_info/geographic_msgs/msg/GeoPoint.msg;/home/koki/ros_catkin_ws/src/geographic_info/geographic_msgs/msg/GeoPointStamped.msg;/home/koki/ros_catkin_ws/src/geographic_info/geographic_msgs/msg/GeoPose.msg;/home/koki/ros_catkin_ws/src/geographic_info/geographic_msgs/msg/GeoPoseStamped.msg;/home/koki/ros_catkin_ws/src/geographic_info/geographic_msgs/msg/KeyValue.msg;/home/koki/ros_catkin_ws/src/geographic_info/geographic_msgs/msg/MapFeature.msg;/home/koki/ros_catkin_ws/src/geographic_info/geographic_msgs/msg/RouteNetwork.msg;/home/koki/ros_catkin_ws/src/geographic_info/geographic_msgs/msg/RoutePath.msg;/home/koki/ros_catkin_ws/src/geographic_info/geographic_msgs/msg/RouteSegment.msg;/home/koki/ros_catkin_ws/src/geographic_info/geographic_msgs/msg/WayPoint.msg"
services_str = "/home/koki/ros_catkin_ws/src/geographic_info/geographic_msgs/srv/GetGeographicMap.srv;/home/koki/ros_catkin_ws/src/geographic_info/geographic_msgs/srv/GetGeoPath.srv;/home/koki/ros_catkin_ws/src/geographic_info/geographic_msgs/srv/GetRoutePlan.srv;/home/koki/ros_catkin_ws/src/geographic_info/geographic_msgs/srv/UpdateGeographicMap.srv"
pkg_name = "geographic_msgs"
dependencies_str = "geometry_msgs;std_msgs;uuid_msgs"
langs = "gencpp;geneus;genlisp;gennodejs;genpy"
dep_include_paths_str = "geographic_msgs;/home/koki/ros_catkin_ws/src/geographic_info/geographic_msgs/msg;geometry_msgs;/home/koki/ros_catkin_ws/install_isolated/share/geometry_msgs/cmake/../msg;std_msgs;/home/koki/ros_catkin_ws/install_isolated/share/std_msgs/cmake/../msg;uuid_msgs;/home/koki/ros_catkin_ws/install_isolated/share/uuid_msgs/cmake/../msg"
PYTHON_EXECUTABLE = "/usr/bin/python3"
package_has_static_sources = '' == 'TRUE'
genmsg_check_deps_script = "/home/koki/ros_catkin_ws/install_isolated/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py"
