# CMake generated Testfile for 
# Source directory: /home/koki/ros_catkin_ws/src/diagnostics/diagnostic_common_diagnostics
# Build directory: /home/koki/ros_catkin_ws/build_isolated/diagnostic_common_diagnostics
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_diagnostic_common_diagnostics_rostest_test_launch_test_cpu_monitor.launch "/home/koki/ros_catkin_ws/build_isolated/diagnostic_common_diagnostics/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/diagnostic_common_diagnostics/test_results/diagnostic_common_diagnostics/rostest-test_launch_test_cpu_monitor.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/diagnostics/diagnostic_common_diagnostics --package=diagnostic_common_diagnostics --results-filename test_launch_test_cpu_monitor.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/diagnostic_common_diagnostics/test_results\" /home/koki/ros_catkin_ws/src/diagnostics/diagnostic_common_diagnostics/test/launch/test_cpu_monitor.launch ")
set_tests_properties(_ctest_diagnostic_common_diagnostics_rostest_test_launch_test_cpu_monitor.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/diagnostics/diagnostic_common_diagnostics/CMakeLists.txt;17;add_rostest;/home/koki/ros_catkin_ws/src/diagnostics/diagnostic_common_diagnostics/CMakeLists.txt;0;")
add_test(_ctest_diagnostic_common_diagnostics_rostest_test_launch_test_cpu_monitor_level_ok.launch "/home/koki/ros_catkin_ws/build_isolated/diagnostic_common_diagnostics/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/diagnostic_common_diagnostics/test_results/diagnostic_common_diagnostics/rostest-test_launch_test_cpu_monitor_level_ok.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/diagnostics/diagnostic_common_diagnostics --package=diagnostic_common_diagnostics --results-filename test_launch_test_cpu_monitor_level_ok.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/diagnostic_common_diagnostics/test_results\" /home/koki/ros_catkin_ws/src/diagnostics/diagnostic_common_diagnostics/test/launch/test_cpu_monitor_level_ok.launch ")
set_tests_properties(_ctest_diagnostic_common_diagnostics_rostest_test_launch_test_cpu_monitor_level_ok.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/diagnostics/diagnostic_common_diagnostics/CMakeLists.txt;18;add_rostest;/home/koki/ros_catkin_ws/src/diagnostics/diagnostic_common_diagnostics/CMakeLists.txt;0;")
add_test(_ctest_diagnostic_common_diagnostics_rostest_test_launch_test_cpu_monitor_level_warn.launch "/home/koki/ros_catkin_ws/build_isolated/diagnostic_common_diagnostics/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/diagnostic_common_diagnostics/test_results/diagnostic_common_diagnostics/rostest-test_launch_test_cpu_monitor_level_warn.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/diagnostics/diagnostic_common_diagnostics --package=diagnostic_common_diagnostics --results-filename test_launch_test_cpu_monitor_level_warn.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/diagnostic_common_diagnostics/test_results\" /home/koki/ros_catkin_ws/src/diagnostics/diagnostic_common_diagnostics/test/launch/test_cpu_monitor_level_warn.launch ")
set_tests_properties(_ctest_diagnostic_common_diagnostics_rostest_test_launch_test_cpu_monitor_level_warn.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/diagnostics/diagnostic_common_diagnostics/CMakeLists.txt;19;add_rostest;/home/koki/ros_catkin_ws/src/diagnostics/diagnostic_common_diagnostics/CMakeLists.txt;0;")
subdirs("gtest")
