# CMake generated Testfile for 
# Source directory: /home/koki/ros_catkin_ws/src/ros_comm/xmlrpcpp/test
# Build directory: /home/koki/ros_catkin_ws/build_isolated/xmlrpcpp/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_xmlrpcpp_gtest_xmlrpcvalue_base64 "/home/koki/ros_catkin_ws/build_isolated/xmlrpcpp/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-xmlrpcvalue_base64.xml" "--return-code" "/home/koki/ros_catkin_ws/devel_isolated/xmlrpcpp/lib/xmlrpcpp/xmlrpcvalue_base64 --gtest_output=xml:/home/koki/ros_catkin_ws/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-xmlrpcvalue_base64.xml")
set_tests_properties(_ctest_xmlrpcpp_gtest_xmlrpcvalue_base64 PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/koki/ros_catkin_ws/src/ros_comm/xmlrpcpp/test/CMakeLists.txt;1;catkin_add_gtest;/home/koki/ros_catkin_ws/src/ros_comm/xmlrpcpp/test/CMakeLists.txt;0;")
add_test(_ctest_xmlrpcpp_gtest_test_base64 "/home/koki/ros_catkin_ws/build_isolated/xmlrpcpp/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-test_base64.xml" "--return-code" "/home/koki/ros_catkin_ws/devel_isolated/xmlrpcpp/lib/xmlrpcpp/test_base64 --gtest_output=xml:/home/koki/ros_catkin_ws/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-test_base64.xml")
set_tests_properties(_ctest_xmlrpcpp_gtest_test_base64 PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/koki/ros_catkin_ws/src/ros_comm/xmlrpcpp/test/CMakeLists.txt;6;catkin_add_gtest;/home/koki/ros_catkin_ws/src/ros_comm/xmlrpcpp/test/CMakeLists.txt;0;")
add_test(_ctest_xmlrpcpp_gtest_HelloTest "/home/koki/ros_catkin_ws/build_isolated/xmlrpcpp/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-HelloTest.xml" "--return-code" "/home/koki/ros_catkin_ws/devel_isolated/xmlrpcpp/lib/xmlrpcpp/HelloTest --gtest_output=xml:/home/koki/ros_catkin_ws/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-HelloTest.xml")
set_tests_properties(_ctest_xmlrpcpp_gtest_HelloTest PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/koki/ros_catkin_ws/src/ros_comm/xmlrpcpp/test/CMakeLists.txt;27;catkin_add_gtest;/home/koki/ros_catkin_ws/src/ros_comm/xmlrpcpp/test/CMakeLists.txt;0;")
add_test(_ctest_xmlrpcpp_gtest_test_dispatch_live "/home/koki/ros_catkin_ws/build_isolated/xmlrpcpp/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-test_dispatch_live.xml" "--return-code" "/home/koki/ros_catkin_ws/devel_isolated/xmlrpcpp/lib/xmlrpcpp/test_dispatch_live --gtest_output=xml:/home/koki/ros_catkin_ws/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-test_dispatch_live.xml")
set_tests_properties(_ctest_xmlrpcpp_gtest_test_dispatch_live PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/koki/ros_catkin_ws/src/ros_comm/xmlrpcpp/test/CMakeLists.txt;32;catkin_add_gtest;/home/koki/ros_catkin_ws/src/ros_comm/xmlrpcpp/test/CMakeLists.txt;0;")
add_test(_ctest_xmlrpcpp_gtest_test_ulimit "/home/koki/ros_catkin_ws/build_isolated/xmlrpcpp/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-test_ulimit.xml" "--return-code" "/home/koki/ros_catkin_ws/devel_isolated/xmlrpcpp/lib/xmlrpcpp/test_ulimit --gtest_output=xml:/home/koki/ros_catkin_ws/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-test_ulimit.xml")
set_tests_properties(_ctest_xmlrpcpp_gtest_test_ulimit PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/koki/ros_catkin_ws/src/ros_comm/xmlrpcpp/test/CMakeLists.txt;37;catkin_add_gtest;/home/koki/ros_catkin_ws/src/ros_comm/xmlrpcpp/test/CMakeLists.txt;0;")
add_test(_ctest_xmlrpcpp_gtest_test_client "/home/koki/ros_catkin_ws/build_isolated/xmlrpcpp/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-test_client.xml" "--return-code" "/home/koki/ros_catkin_ws/devel_isolated/xmlrpcpp/lib/xmlrpcpp/test_client --gtest_output=xml:/home/koki/ros_catkin_ws/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-test_client.xml")
set_tests_properties(_ctest_xmlrpcpp_gtest_test_client PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/koki/ros_catkin_ws/src/ros_comm/xmlrpcpp/test/CMakeLists.txt;46;catkin_add_gtest;/home/koki/ros_catkin_ws/src/ros_comm/xmlrpcpp/test/CMakeLists.txt;0;")
add_test(_ctest_xmlrpcpp_gtest_test_dispatch "/home/koki/ros_catkin_ws/build_isolated/xmlrpcpp/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-test_dispatch.xml" "--return-code" "/home/koki/ros_catkin_ws/devel_isolated/xmlrpcpp/lib/xmlrpcpp/test_dispatch --gtest_output=xml:/home/koki/ros_catkin_ws/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-test_dispatch.xml")
set_tests_properties(_ctest_xmlrpcpp_gtest_test_dispatch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/koki/ros_catkin_ws/src/ros_comm/xmlrpcpp/test/CMakeLists.txt;68;catkin_add_gtest;/home/koki/ros_catkin_ws/src/ros_comm/xmlrpcpp/test/CMakeLists.txt;0;")
add_test(_ctest_xmlrpcpp_gtest_test_socket "/home/koki/ros_catkin_ws/build_isolated/xmlrpcpp/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-test_socket.xml" "--return-code" "/home/koki/ros_catkin_ws/devel_isolated/xmlrpcpp/lib/xmlrpcpp/test_socket --gtest_output=xml:/home/koki/ros_catkin_ws/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-test_socket.xml")
set_tests_properties(_ctest_xmlrpcpp_gtest_test_socket PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/koki/ros_catkin_ws/src/ros_comm/xmlrpcpp/test/CMakeLists.txt;101;catkin_add_gtest;/home/koki/ros_catkin_ws/src/ros_comm/xmlrpcpp/test/CMakeLists.txt;0;")
add_test(_ctest_xmlrpcpp_gtest_TestValues "/home/koki/ros_catkin_ws/build_isolated/xmlrpcpp/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-TestValues.xml" "--return-code" "/home/koki/ros_catkin_ws/devel_isolated/xmlrpcpp/lib/xmlrpcpp/TestValues --gtest_output=xml:/home/koki/ros_catkin_ws/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-TestValues.xml")
set_tests_properties(_ctest_xmlrpcpp_gtest_TestValues PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/koki/ros_catkin_ws/src/ros_comm/xmlrpcpp/test/CMakeLists.txt;120;catkin_add_gtest;/home/koki/ros_catkin_ws/src/ros_comm/xmlrpcpp/test/CMakeLists.txt;0;")
add_test(_ctest_xmlrpcpp_gtest_test_util "/home/koki/ros_catkin_ws/build_isolated/xmlrpcpp/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-test_util.xml" "--return-code" "/home/koki/ros_catkin_ws/devel_isolated/xmlrpcpp/lib/xmlrpcpp/test_util --gtest_output=xml:/home/koki/ros_catkin_ws/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-test_util.xml")
set_tests_properties(_ctest_xmlrpcpp_gtest_test_util PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/koki/ros_catkin_ws/src/ros_comm/xmlrpcpp/test/CMakeLists.txt;125;catkin_add_gtest;/home/koki/ros_catkin_ws/src/ros_comm/xmlrpcpp/test/CMakeLists.txt;0;")
add_test(_ctest_xmlrpcpp_gtest_TestXml "/home/koki/ros_catkin_ws/build_isolated/xmlrpcpp/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-TestXml.xml" "--return-code" "/home/koki/ros_catkin_ws/devel_isolated/xmlrpcpp/lib/xmlrpcpp/TestXml --gtest_output=xml:/home/koki/ros_catkin_ws/build_isolated/xmlrpcpp/test_results/xmlrpcpp/gtest-TestXml.xml")
set_tests_properties(_ctest_xmlrpcpp_gtest_TestXml PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/koki/ros_catkin_ws/src/ros_comm/xmlrpcpp/test/CMakeLists.txt;130;catkin_add_gtest;/home/koki/ros_catkin_ws/src/ros_comm/xmlrpcpp/test/CMakeLists.txt;0;")
