# CMake generated Testfile for 
# Source directory: /home/koki/ros_catkin_ws/src/dynamic_reconfigure/test
# Build directory: /home/koki/ros_catkin_ws/build_isolated/dynamic_reconfigure/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_dynamic_reconfigure_rostest_test_test_cpp_simple_client.launch "/home/koki/ros_catkin_ws/build_isolated/dynamic_reconfigure/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/dynamic_reconfigure/test_results/dynamic_reconfigure/rostest-test_test_cpp_simple_client.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/dynamic_reconfigure --package=dynamic_reconfigure --results-filename test_test_cpp_simple_client.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/dynamic_reconfigure/test_results\" /home/koki/ros_catkin_ws/src/dynamic_reconfigure/test/test_cpp_simple_client.launch ")
set_tests_properties(_ctest_dynamic_reconfigure_rostest_test_test_cpp_simple_client.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;80;add_rostest;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;100;_add_rostest_google_test;/home/koki/ros_catkin_ws/src/dynamic_reconfigure/test/CMakeLists.txt;7;add_rostest_gtest;/home/koki/ros_catkin_ws/src/dynamic_reconfigure/test/CMakeLists.txt;0;")
add_test(_ctest_dynamic_reconfigure_rostest_test_test_python_simple_client.launch "/home/koki/ros_catkin_ws/build_isolated/dynamic_reconfigure/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/dynamic_reconfigure/test_results/dynamic_reconfigure/rostest-test_test_python_simple_client.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/dynamic_reconfigure --package=dynamic_reconfigure --results-filename test_test_python_simple_client.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/dynamic_reconfigure/test_results\" /home/koki/ros_catkin_ws/src/dynamic_reconfigure/test/test_python_simple_client.launch ")
set_tests_properties(_ctest_dynamic_reconfigure_rostest_test_test_python_simple_client.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/dynamic_reconfigure/test/CMakeLists.txt;13;add_rostest;/home/koki/ros_catkin_ws/src/dynamic_reconfigure/test/CMakeLists.txt;0;")
