set(_CATKIN_CURRENT_PACKAGE "bondcpp")
set(bondcpp_VERSION "1.8.6")
set(bondcpp_MAINTAINER "Michael Carroll <michael@openrobotics.org>")
set(bondcpp_PACKAGE_FORMAT "2")
set(bondcpp_BUILD_DEPENDS "cmake_modules" "bond" "libboost-dev" "libboost-date-time-dev" "libboost-thread-dev" "roscpp" "smclib" "uuid")
set(bondcpp_BUILD_DEPENDS_cmake_modules_VERSION_GTE "0.3.2")
set(bondcpp_BUILD_EXPORT_DEPENDS "bond" "libboost-dev" "libboost-date-time-dev" "libboost-thread-dev" "roscpp" "smclib" "uuid")
set(bondcpp_BUILDTOOL_DEPENDS "catkin")
set(bondcpp_BUILDTOOL_EXPORT_DEPENDS )
set(bondcpp_EXEC_DEPENDS "bond" "libboost-dev" "libboost-date-time-dev" "libboost-thread-dev" "roscpp" "smclib" "uuid")
set(bondcpp_RUN_DEPENDS "bond" "libboost-dev" "libboost-date-time-dev" "libboost-thread-dev" "roscpp" "smclib" "uuid")
set(bondcpp_TEST_DEPENDS )
set(bondcpp_DOC_DEPENDS )
set(bondcpp_URL_WEBSITE "http://www.ros.org/wiki/bondcpp")
set(bondcpp_URL_BUGTRACKER "https://github.com/ros/bond_core/issues")
set(bondcpp_URL_REPOSITORY "https://github.com/ros/bond_core")
set(bondcpp_DEPRECATED "")