# CMake generated Testfile for 
# Source directory: /home/koki/ros_catkin_ws/src/perception_pcl/pcl_ros
# Build directory: /home/koki/ros_catkin_ws/build_isolated/pcl_ros
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_pcl_ros_rostest_tests_test_tf_message_filter_pcl.launch "/home/koki/ros_catkin_ws/build_isolated/pcl_ros/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/pcl_ros/test_results/pcl_ros/rostest-tests_test_tf_message_filter_pcl.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/perception_pcl/pcl_ros --package=pcl_ros --results-filename tests_test_tf_message_filter_pcl.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/pcl_ros/test_results\" /home/koki/ros_catkin_ws/src/perception_pcl/pcl_ros/tests/test_tf_message_filter_pcl.launch ")
set_tests_properties(_ctest_pcl_ros_rostest_tests_test_tf_message_filter_pcl.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;80;add_rostest;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;100;_add_rostest_google_test;/home/koki/ros_catkin_ws/src/perception_pcl/pcl_ros/CMakeLists.txt;230;add_rostest_gtest;/home/koki/ros_catkin_ws/src/perception_pcl/pcl_ros/CMakeLists.txt;0;")
add_test(_ctest_pcl_ros_rostest_sample_normal_3d__gui_false.launch "/home/koki/ros_catkin_ws/build_isolated/pcl_ros/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/pcl_ros/test_results/pcl_ros/rostest-sample_normal_3d__gui_false.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/perception_pcl/pcl_ros --package=pcl_ros --results-filename sample_normal_3d__gui_false.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/pcl_ros/test_results\" /home/koki/ros_catkin_ws/src/perception_pcl/pcl_ros/samples/pcl_ros/features/sample_normal_3d.launch gui:=false")
set_tests_properties(_ctest_pcl_ros_rostest_sample_normal_3d__gui_false.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/perception_pcl/pcl_ros/CMakeLists.txt;232;add_rostest;/home/koki/ros_catkin_ws/src/perception_pcl/pcl_ros/CMakeLists.txt;0;")
add_test(_ctest_pcl_ros_rostest_sample_statistical_outlier_removal__gui_false.launch "/home/koki/ros_catkin_ws/build_isolated/pcl_ros/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/pcl_ros/test_results/pcl_ros/rostest-sample_statistical_outlier_removal__gui_false.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/perception_pcl/pcl_ros --package=pcl_ros --results-filename sample_statistical_outlier_removal__gui_false.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/pcl_ros/test_results\" /home/koki/ros_catkin_ws/src/perception_pcl/pcl_ros/samples/pcl_ros/filters/sample_statistical_outlier_removal.launch gui:=false")
set_tests_properties(_ctest_pcl_ros_rostest_sample_statistical_outlier_removal__gui_false.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/perception_pcl/pcl_ros/CMakeLists.txt;233;add_rostest;/home/koki/ros_catkin_ws/src/perception_pcl/pcl_ros/CMakeLists.txt;0;")
add_test(_ctest_pcl_ros_rostest_sample_voxel_grid__gui_false.launch "/home/koki/ros_catkin_ws/build_isolated/pcl_ros/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/pcl_ros/test_results/pcl_ros/rostest-sample_voxel_grid__gui_false.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/perception_pcl/pcl_ros --package=pcl_ros --results-filename sample_voxel_grid__gui_false.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/pcl_ros/test_results\" /home/koki/ros_catkin_ws/src/perception_pcl/pcl_ros/samples/pcl_ros/filters/sample_voxel_grid.launch gui:=false")
set_tests_properties(_ctest_pcl_ros_rostest_sample_voxel_grid__gui_false.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/perception_pcl/pcl_ros/CMakeLists.txt;234;add_rostest;/home/koki/ros_catkin_ws/src/perception_pcl/pcl_ros/CMakeLists.txt;0;")
add_test(_ctest_pcl_ros_rostest_sample_extract_clusters__gui_false.launch "/home/koki/ros_catkin_ws/build_isolated/pcl_ros/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/pcl_ros/test_results/pcl_ros/rostest-sample_extract_clusters__gui_false.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/perception_pcl/pcl_ros --package=pcl_ros --results-filename sample_extract_clusters__gui_false.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/pcl_ros/test_results\" /home/koki/ros_catkin_ws/src/perception_pcl/pcl_ros/samples/pcl_ros/segmentation/sample_extract_clusters.launch gui:=false")
set_tests_properties(_ctest_pcl_ros_rostest_sample_extract_clusters__gui_false.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/perception_pcl/pcl_ros/CMakeLists.txt;235;add_rostest;/home/koki/ros_catkin_ws/src/perception_pcl/pcl_ros/CMakeLists.txt;0;")
add_test(_ctest_pcl_ros_rostest_sample_convex_hull__gui_false.launch "/home/koki/ros_catkin_ws/build_isolated/pcl_ros/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/pcl_ros/test_results/pcl_ros/rostest-sample_convex_hull__gui_false.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/perception_pcl/pcl_ros --package=pcl_ros --results-filename sample_convex_hull__gui_false.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/pcl_ros/test_results\" /home/koki/ros_catkin_ws/src/perception_pcl/pcl_ros/samples/pcl_ros/surface/sample_convex_hull.launch gui:=false")
set_tests_properties(_ctest_pcl_ros_rostest_sample_convex_hull__gui_false.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/perception_pcl/pcl_ros/CMakeLists.txt;236;add_rostest;/home/koki/ros_catkin_ws/src/perception_pcl/pcl_ros/CMakeLists.txt;0;")
subdirs("gtest")
