# CMake generated Testfile for 
# Source directory: /home/koki/ros_catkin_ws/src/geometry2/tf2_ros
# Build directory: /home/koki/ros_catkin_ws/build_isolated/tf2_ros
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_tf2_ros_rostest_test_transform_listener_unittest.launch "/home/koki/ros_catkin_ws/build_isolated/tf2_ros/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/tf2_ros/test_results/tf2_ros/rostest-test_transform_listener_unittest.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/geometry2/tf2_ros --package=tf2_ros --results-filename test_transform_listener_unittest.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/tf2_ros/test_results\" /home/koki/ros_catkin_ws/src/geometry2/tf2_ros/test/transform_listener_unittest.launch ")
set_tests_properties(_ctest_tf2_ros_rostest_test_transform_listener_unittest.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/geometry2/tf2_ros/CMakeLists.txt;149;add_rostest;/home/koki/ros_catkin_ws/src/geometry2/tf2_ros/CMakeLists.txt;0;")
add_test(_ctest_tf2_ros_rostest_test_transform_listener_time_reset_test.launch "/home/koki/ros_catkin_ws/build_isolated/tf2_ros/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/tf2_ros/test_results/tf2_ros/rostest-test_transform_listener_time_reset_test.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/geometry2/tf2_ros --package=tf2_ros --results-filename test_transform_listener_time_reset_test.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/tf2_ros/test_results\" /home/koki/ros_catkin_ws/src/geometry2/tf2_ros/test/transform_listener_time_reset_test.launch ")
set_tests_properties(_ctest_tf2_ros_rostest_test_transform_listener_time_reset_test.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/geometry2/tf2_ros/CMakeLists.txt;150;add_rostest;/home/koki/ros_catkin_ws/src/geometry2/tf2_ros/CMakeLists.txt;0;")
add_test(_ctest_tf2_ros_rostest_test_message_filter_test.launch "/home/koki/ros_catkin_ws/build_isolated/tf2_ros/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/tf2_ros/test_results/tf2_ros/rostest-test_message_filter_test.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/geometry2/tf2_ros --package=tf2_ros --results-filename test_message_filter_test.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/tf2_ros/test_results\" /home/koki/ros_catkin_ws/src/geometry2/tf2_ros/test/message_filter_test.launch ")
set_tests_properties(_ctest_tf2_ros_rostest_test_message_filter_test.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/geometry2/tf2_ros/CMakeLists.txt;151;add_rostest;/home/koki/ros_catkin_ws/src/geometry2/tf2_ros/CMakeLists.txt;0;")
subdirs("gtest")
