set(_CATKIN_CURRENT_PACKAGE "opencv3")
set(opencv3_VERSION "0.0.0")
set(opencv3_MAINTAINER "Chris Lalancette <clalancette@openrobotics.org>")
set(opencv3_PACKAGE_FORMAT "2")
set(opencv3_BUILD_DEPENDS )
set(opencv3_BUILD_EXPORT_DEPENDS "libopencv-dev")
set(opencv3_BUILDTOOL_DEPENDS "catkin")
set(opencv3_BUILDTOOL_EXPORT_DEPENDS )
set(opencv3_EXEC_DEPENDS "libopencv-dev")
set(opencv3_RUN_DEPENDS "libopencv-dev")
set(opencv3_TEST_DEPENDS )
set(opencv3_DOC_DEPENDS )
set(opencv3_URL_WEBSITE "")
set(opencv3_URL_BUGTRACKER "")
set(opencv3_URL_REPOSITORY "")
set(opencv3_DEPRECATED "")