# CMake generated Testfile for 
# Source directory: /home/koki/ros_catkin_ws/src/executive_smach/smach_ros
# Build directory: /home/koki/ros_catkin_ws/build_isolated/smach_ros
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_smach_ros_rostest_test_state_machine.test "/home/koki/ros_catkin_ws/build_isolated/smach_ros/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/smach_ros/test_results/smach_ros/rostest-test_state_machine.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/executive_smach/smach_ros --package=smach_ros --results-filename test_state_machine.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/smach_ros/test_results\" /home/koki/ros_catkin_ws/src/executive_smach/smach_ros/test/state_machine.test ")
set_tests_properties(_ctest_smach_ros_rostest_test_state_machine.test PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/executive_smach/smach_ros/CMakeLists.txt;15;add_rostest;/home/koki/ros_catkin_ws/src/executive_smach/smach_ros/CMakeLists.txt;0;")
add_test(_ctest_smach_ros_rostest_test_sequence.test "/home/koki/ros_catkin_ws/build_isolated/smach_ros/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/smach_ros/test_results/smach_ros/rostest-test_sequence.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/executive_smach/smach_ros --package=smach_ros --results-filename test_sequence.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/smach_ros/test_results\" /home/koki/ros_catkin_ws/src/executive_smach/smach_ros/test/sequence.test ")
set_tests_properties(_ctest_smach_ros_rostest_test_sequence.test PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/executive_smach/smach_ros/CMakeLists.txt;16;add_rostest;/home/koki/ros_catkin_ws/src/executive_smach/smach_ros/CMakeLists.txt;0;")
add_test(_ctest_smach_ros_rostest_test_concurrence.test "/home/koki/ros_catkin_ws/build_isolated/smach_ros/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/smach_ros/test_results/smach_ros/rostest-test_concurrence.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/executive_smach/smach_ros --package=smach_ros --results-filename test_concurrence.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/smach_ros/test_results\" /home/koki/ros_catkin_ws/src/executive_smach/smach_ros/test/concurrence.test ")
set_tests_properties(_ctest_smach_ros_rostest_test_concurrence.test PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/executive_smach/smach_ros/CMakeLists.txt;17;add_rostest;/home/koki/ros_catkin_ws/src/executive_smach/smach_ros/CMakeLists.txt;0;")
add_test(_ctest_smach_ros_rostest_test_introspection.test "/home/koki/ros_catkin_ws/build_isolated/smach_ros/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/smach_ros/test_results/smach_ros/rostest-test_introspection.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/executive_smach/smach_ros --package=smach_ros --results-filename test_introspection.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/smach_ros/test_results\" /home/koki/ros_catkin_ws/src/executive_smach/smach_ros/test/introspection.test ")
set_tests_properties(_ctest_smach_ros_rostest_test_introspection.test PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/executive_smach/smach_ros/CMakeLists.txt;18;add_rostest;/home/koki/ros_catkin_ws/src/executive_smach/smach_ros/CMakeLists.txt;0;")
add_test(_ctest_smach_ros_rostest_test_smach_actionlib.test "/home/koki/ros_catkin_ws/build_isolated/smach_ros/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/smach_ros/test_results/smach_ros/rostest-test_smach_actionlib.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/executive_smach/smach_ros --package=smach_ros --results-filename test_smach_actionlib.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/smach_ros/test_results\" /home/koki/ros_catkin_ws/src/executive_smach/smach_ros/test/smach_actionlib.test ")
set_tests_properties(_ctest_smach_ros_rostest_test_smach_actionlib.test PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/executive_smach/smach_ros/CMakeLists.txt;19;add_rostest;/home/koki/ros_catkin_ws/src/executive_smach/smach_ros/CMakeLists.txt;0;")
add_test(_ctest_smach_ros_rostest_test_monitor.test "/home/koki/ros_catkin_ws/build_isolated/smach_ros/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/smach_ros/test_results/smach_ros/rostest-test_monitor.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/executive_smach/smach_ros --package=smach_ros --results-filename test_monitor.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/smach_ros/test_results\" /home/koki/ros_catkin_ws/src/executive_smach/smach_ros/test/monitor.test ")
set_tests_properties(_ctest_smach_ros_rostest_test_monitor.test PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/executive_smach/smach_ros/CMakeLists.txt;20;add_rostest;/home/koki/ros_catkin_ws/src/executive_smach/smach_ros/CMakeLists.txt;0;")
subdirs("gtest")
