# CMake generated Testfile for 
# Source directory: /home/koki/ros_catkin_ws/src/ros_comm/rostopic
# Build directory: /home/koki/ros_catkin_ws/build_isolated/rostopic
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_rostopic_rostest_test_rostopic.test "/home/koki/ros_catkin_ws/build_isolated/rostopic/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/rostopic/test_results/rostopic/rostest-test_rostopic.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/ros_comm/rostopic --package=rostopic --results-filename test_rostopic.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/rostopic/test_results\" /home/koki/ros_catkin_ws/src/ros_comm/rostopic/test/rostopic.test ")
set_tests_properties(_ctest_rostopic_rostest_test_rostopic.test PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/ros_comm/rostopic/CMakeLists.txt;13;add_rostest;/home/koki/ros_catkin_ws/src/ros_comm/rostopic/CMakeLists.txt;0;")
add_test(_ctest_rostopic_nosetests_test.test_rostopic_command_line_offline.py "/home/koki/ros_catkin_ws/build_isolated/rostopic/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/rostopic/test_results/rostopic/nosetests-test.test_rostopic_command_line_offline.py.xml" "--return-code" "\"/home/koki/.local/lib/python3.6/site-packages/cmake/data/bin/cmake\" -E make_directory /home/koki/ros_catkin_ws/build_isolated/rostopic/test_results/rostopic" "/usr/bin/nosetests3 -P --process-timeout=60 /home/koki/ros_catkin_ws/src/ros_comm/rostopic/test/test_rostopic_command_line_offline.py --with-xunit --xunit-file=/home/koki/ros_catkin_ws/build_isolated/rostopic/test_results/rostopic/nosetests-test.test_rostopic_command_line_offline.py.xml")
set_tests_properties(_ctest_rostopic_nosetests_test.test_rostopic_command_line_offline.py PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/nosetests.cmake;83;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/ros_comm/rostopic/CMakeLists.txt;15;catkin_add_nosetests;/home/koki/ros_catkin_ws/src/ros_comm/rostopic/CMakeLists.txt;0;")
subdirs("gtest")
