# CMake generated Testfile for 
# Source directory: /home/koki/ros_catkin_ws/src/ros_tutorials/rospy_tutorials
# Build directory: /home/koki/ros_catkin_ws/build_isolated/rospy_tutorials
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_rospy_tutorials_rostest_test_test-add-two-ints.launch "/home/koki/ros_catkin_ws/build_isolated/rospy_tutorials/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/rospy_tutorials/test_results/rospy_tutorials/rostest-test_test-add-two-ints.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/ros_tutorials/rospy_tutorials --package=rospy_tutorials --results-filename test_test-add-two-ints.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/rospy_tutorials/test_results\" /home/koki/ros_catkin_ws/src/ros_tutorials/rospy_tutorials/test/test-add-two-ints.launch ")
set_tests_properties(_ctest_rospy_tutorials_rostest_test_test-add-two-ints.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/ros_tutorials/rospy_tutorials/CMakeLists.txt;112;add_rostest;/home/koki/ros_catkin_ws/src/ros_tutorials/rospy_tutorials/CMakeLists.txt;0;")
add_test(_ctest_rospy_tutorials_rostest_test_test-peer-subscribe-notify.launch "/home/koki/ros_catkin_ws/build_isolated/rospy_tutorials/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/rospy_tutorials/test_results/rospy_tutorials/rostest-test_test-peer-subscribe-notify.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/ros_tutorials/rospy_tutorials --package=rospy_tutorials --results-filename test_test-peer-subscribe-notify.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/rospy_tutorials/test_results\" /home/koki/ros_catkin_ws/src/ros_tutorials/rospy_tutorials/test/test-peer-subscribe-notify.launch ")
set_tests_properties(_ctest_rospy_tutorials_rostest_test_test-peer-subscribe-notify.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/ros_tutorials/rospy_tutorials/CMakeLists.txt;112;add_rostest;/home/koki/ros_catkin_ws/src/ros_tutorials/rospy_tutorials/CMakeLists.txt;0;")
add_test(_ctest_rospy_tutorials_rostest_test_test-add-two-ints-with-roscpp-server.launch "/home/koki/ros_catkin_ws/build_isolated/rospy_tutorials/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/rospy_tutorials/test_results/rospy_tutorials/rostest-test_test-add-two-ints-with-roscpp-server.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/ros_tutorials/rospy_tutorials --package=rospy_tutorials --results-filename test_test-add-two-ints-with-roscpp-server.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/rospy_tutorials/test_results\" /home/koki/ros_catkin_ws/src/ros_tutorials/rospy_tutorials/test/test-add-two-ints-with-roscpp-server.launch ")
set_tests_properties(_ctest_rospy_tutorials_rostest_test_test-add-two-ints-with-roscpp-server.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/ros_tutorials/rospy_tutorials/CMakeLists.txt;112;add_rostest;/home/koki/ros_catkin_ws/src/ros_tutorials/rospy_tutorials/CMakeLists.txt;0;")
add_test(_ctest_rospy_tutorials_rostest_test_test-talker-listener.launch "/home/koki/ros_catkin_ws/build_isolated/rospy_tutorials/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/rospy_tutorials/test_results/rospy_tutorials/rostest-test_test-talker-listener.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/ros_tutorials/rospy_tutorials --package=rospy_tutorials --results-filename test_test-talker-listener.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/rospy_tutorials/test_results\" /home/koki/ros_catkin_ws/src/ros_tutorials/rospy_tutorials/test/test-talker-listener.launch ")
set_tests_properties(_ctest_rospy_tutorials_rostest_test_test-talker-listener.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/ros_tutorials/rospy_tutorials/CMakeLists.txt;112;add_rostest;/home/koki/ros_catkin_ws/src/ros_tutorials/rospy_tutorials/CMakeLists.txt;0;")
add_test(_ctest_rospy_tutorials_rostest_test_test-talker-listener-with-roscpp.launch "/home/koki/ros_catkin_ws/build_isolated/rospy_tutorials/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/rospy_tutorials/test_results/rospy_tutorials/rostest-test_test-talker-listener-with-roscpp.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/ros_tutorials/rospy_tutorials --package=rospy_tutorials --results-filename test_test-talker-listener-with-roscpp.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/rospy_tutorials/test_results\" /home/koki/ros_catkin_ws/src/ros_tutorials/rospy_tutorials/test/test-talker-listener-with-roscpp.launch ")
set_tests_properties(_ctest_rospy_tutorials_rostest_test_test-talker-listener-with-roscpp.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/ros_tutorials/rospy_tutorials/CMakeLists.txt;112;add_rostest;/home/koki/ros_catkin_ws/src/ros_tutorials/rospy_tutorials/CMakeLists.txt;0;")
add_test(_ctest_rospy_tutorials_rostest_test_test-talker-listener-with-timer.launch "/home/koki/ros_catkin_ws/build_isolated/rospy_tutorials/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/rospy_tutorials/test_results/rospy_tutorials/rostest-test_test-talker-listener-with-timer.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/ros_tutorials/rospy_tutorials --package=rospy_tutorials --results-filename test_test-talker-listener-with-timer.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/rospy_tutorials/test_results\" /home/koki/ros_catkin_ws/src/ros_tutorials/rospy_tutorials/test/test-talker-listener-with-timer.launch ")
set_tests_properties(_ctest_rospy_tutorials_rostest_test_test-talker-listener-with-timer.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/ros_tutorials/rospy_tutorials/CMakeLists.txt;112;add_rostest;/home/koki/ros_catkin_ws/src/ros_tutorials/rospy_tutorials/CMakeLists.txt;0;")
add_test(_ctest_rospy_tutorials_rostest_test_test-on-shutdown.launch "/home/koki/ros_catkin_ws/build_isolated/rospy_tutorials/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/rospy_tutorials/test_results/rospy_tutorials/rostest-test_test-on-shutdown.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/ros_tutorials/rospy_tutorials --package=rospy_tutorials --results-filename test_test-on-shutdown.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/rospy_tutorials/test_results\" /home/koki/ros_catkin_ws/src/ros_tutorials/rospy_tutorials/test/test-on-shutdown.launch ")
set_tests_properties(_ctest_rospy_tutorials_rostest_test_test-on-shutdown.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/ros_tutorials/rospy_tutorials/CMakeLists.txt;112;add_rostest;/home/koki/ros_catkin_ws/src/ros_tutorials/rospy_tutorials/CMakeLists.txt;0;")
add_test(_ctest_rospy_tutorials_rostest_test_test-connection-header.launch "/home/koki/ros_catkin_ws/build_isolated/rospy_tutorials/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/rospy_tutorials/test_results/rospy_tutorials/rostest-test_test-connection-header.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/ros_tutorials/rospy_tutorials --package=rospy_tutorials --results-filename test_test-connection-header.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/rospy_tutorials/test_results\" /home/koki/ros_catkin_ws/src/ros_tutorials/rospy_tutorials/test/test-connection-header.launch ")
set_tests_properties(_ctest_rospy_tutorials_rostest_test_test-connection-header.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/ros_tutorials/rospy_tutorials/CMakeLists.txt;112;add_rostest;/home/koki/ros_catkin_ws/src/ros_tutorials/rospy_tutorials/CMakeLists.txt;0;")
subdirs("gtest")
