# CMake generated Testfile for 
# Source directory: /home/koki/ros_catkin_ws/src/interactive_markers
# Build directory: /home/koki/ros_catkin_ws/build_isolated/interactive_markers
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_interactive_markers_rostest_test_cpp_server.test "/home/koki/ros_catkin_ws/build_isolated/interactive_markers/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/interactive_markers/test_results/interactive_markers/rostest-test_cpp_server.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/interactive_markers --package=interactive_markers --results-filename test_cpp_server.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/interactive_markers/test_results\" /home/koki/ros_catkin_ws/src/interactive_markers/test/cpp_server.test ")
set_tests_properties(_ctest_interactive_markers_rostest_test_cpp_server.test PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/interactive_markers/CMakeLists.txt;55;add_rostest;/home/koki/ros_catkin_ws/src/interactive_markers/CMakeLists.txt;0;")
add_test(_ctest_interactive_markers_rostest_test_cpp_client.test "/home/koki/ros_catkin_ws/build_isolated/interactive_markers/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/interactive_markers/test_results/interactive_markers/rostest-test_cpp_client.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/interactive_markers --package=interactive_markers --results-filename test_cpp_client.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/interactive_markers/test_results\" /home/koki/ros_catkin_ws/src/interactive_markers/test/cpp_client.test ")
set_tests_properties(_ctest_interactive_markers_rostest_test_cpp_client.test PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/interactive_markers/CMakeLists.txt;60;add_rostest;/home/koki/ros_catkin_ws/src/interactive_markers/CMakeLists.txt;0;")
add_test(_ctest_interactive_markers_rostest_test_cpp_server_client.test "/home/koki/ros_catkin_ws/build_isolated/interactive_markers/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/interactive_markers/test_results/interactive_markers/rostest-test_cpp_server_client.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/interactive_markers --package=interactive_markers --results-filename test_cpp_server_client.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/interactive_markers/test_results\" /home/koki/ros_catkin_ws/src/interactive_markers/test/cpp_server_client.test ")
set_tests_properties(_ctest_interactive_markers_rostest_test_cpp_server_client.test PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/interactive_markers/CMakeLists.txt;65;add_rostest;/home/koki/ros_catkin_ws/src/interactive_markers/CMakeLists.txt;0;")
subdirs("gtest")
