# CMake generated Testfile for 
# Source directory: /home/koki/ros_catkin_ws/src/urdfdom_py
# Build directory: /home/koki/ros_catkin_ws/build_isolated/urdfdom_py
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_urdfdom_py_nosetests_test.test_urdf.py "/home/koki/ros_catkin_ws/build_isolated/urdfdom_py/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/urdfdom_py/test_results/urdfdom_py/nosetests-test.test_urdf.py.xml" "--return-code" "\"/home/koki/.local/lib/python3.6/site-packages/cmake/data/bin/cmake\" -E make_directory /home/koki/ros_catkin_ws/build_isolated/urdfdom_py/test_results/urdfdom_py" "/usr/bin/nosetests3 -P --process-timeout=60 /home/koki/ros_catkin_ws/src/urdfdom_py/test/test_urdf.py --with-xunit --xunit-file=/home/koki/ros_catkin_ws/build_isolated/urdfdom_py/test_results/urdfdom_py/nosetests-test.test_urdf.py.xml")
set_tests_properties(_ctest_urdfdom_py_nosetests_test.test_urdf.py PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/nosetests.cmake;83;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/urdfdom_py/CMakeLists.txt;15;catkin_add_nosetests;/home/koki/ros_catkin_ws/src/urdfdom_py/CMakeLists.txt;0;")
add_test(_ctest_urdfdom_py_nosetests_test.test_urdf_error.py "/home/koki/ros_catkin_ws/build_isolated/urdfdom_py/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/urdfdom_py/test_results/urdfdom_py/nosetests-test.test_urdf_error.py.xml" "--return-code" "\"/home/koki/.local/lib/python3.6/site-packages/cmake/data/bin/cmake\" -E make_directory /home/koki/ros_catkin_ws/build_isolated/urdfdom_py/test_results/urdfdom_py" "/usr/bin/nosetests3 -P --process-timeout=60 /home/koki/ros_catkin_ws/src/urdfdom_py/test/test_urdf_error.py --with-xunit --xunit-file=/home/koki/ros_catkin_ws/build_isolated/urdfdom_py/test_results/urdfdom_py/nosetests-test.test_urdf_error.py.xml")
set_tests_properties(_ctest_urdfdom_py_nosetests_test.test_urdf_error.py PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/nosetests.cmake;83;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/urdfdom_py/CMakeLists.txt;16;catkin_add_nosetests;/home/koki/ros_catkin_ws/src/urdfdom_py/CMakeLists.txt;0;")
subdirs("gtest")
