set(kdl_parser_py_SETUP_PY_SETUP_MODULE "distutils.core")
set(kdl_parser_py_SETUP_PY_VERSION "1.13.1")
set(kdl_parser_py_SETUP_PY_SCRIPTS "")
set(kdl_parser_py_SETUP_PY_PACKAGES "kdl_parser_py")
set(kdl_parser_py_SETUP_PY_PACKAGE_DIRS "kdl_parser_py")
set(kdl_parser_py_SETUP_PY_MODULES "")
set(kdl_parser_py_SETUP_PY_MODULE_DIRS "")