set(_CATKIN_CURRENT_PACKAGE "rqt_rviz")
set(rqt_rviz_VERSION "0.6.0")
set(rqt_rviz_MAINTAINER "Louise Poubel <louise@osrfoundation.org>")
set(rqt_rviz_PACKAGE_FORMAT "1")
set(rqt_rviz_BUILD_DEPENDS "boost" "pluginlib" "qtbase5-dev" "rqt_gui" "rqt_gui_cpp" "rviz")
set(rqt_rviz_BUILD_EXPORT_DEPENDS "boost" "pluginlib" "rqt_gui" "rqt_gui_cpp" "rviz")
set(rqt_rviz_BUILDTOOL_DEPENDS "catkin")
set(rqt_rviz_BUILDTOOL_EXPORT_DEPENDS )
set(rqt_rviz_EXEC_DEPENDS "boost" "pluginlib" "rqt_gui" "rqt_gui_cpp" "rviz")
set(rqt_rviz_RUN_DEPENDS "boost" "pluginlib" "rqt_gui" "rqt_gui_cpp" "rviz")
set(rqt_rviz_TEST_DEPENDS )
set(rqt_rviz_DOC_DEPENDS )
set(rqt_rviz_URL_WEBSITE "http://wiki.ros.org/rqt_rviz")
set(rqt_rviz_URL_BUGTRACKER "https://github.com/ros-visualization/rqt_rviz/issues")
set(rqt_rviz_URL_REPOSITORY "https://github.com/ros-visualization/rqt_rviz")
set(rqt_rviz_DEPRECATED "")