# CMake generated Testfile for 
# Source directory: /home/koki/ros_catkin_ws/src/diagnostics/test_diagnostic_aggregator
# Build directory: /home/koki/ros_catkin_ws/build_isolated/test_diagnostic_aggregator
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_test_diagnostic_aggregator_rostest_test_launch_test_match_no_analyze_analyzer_load.launch "/home/koki/ros_catkin_ws/build_isolated/test_diagnostic_aggregator/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/test_diagnostic_aggregator/test_results/test_diagnostic_aggregator/rostest-test_launch_test_match_no_analyze_analyzer_load.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/diagnostics/test_diagnostic_aggregator --package=test_diagnostic_aggregator --results-filename test_launch_test_match_no_analyze_analyzer_load.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/test_diagnostic_aggregator/test_results\" /home/koki/ros_catkin_ws/src/diagnostics/test_diagnostic_aggregator/test/launch/test_match_no_analyze_analyzer_load.launch ")
set_tests_properties(_ctest_test_diagnostic_aggregator_rostest_test_launch_test_match_no_analyze_analyzer_load.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/diagnostics/test_diagnostic_aggregator/CMakeLists.txt;22;add_rostest;/home/koki/ros_catkin_ws/src/diagnostics/test_diagnostic_aggregator/CMakeLists.txt;0;")
add_test(_ctest_test_diagnostic_aggregator_rostest_test_launch_test_match_no_analyze.launch "/home/koki/ros_catkin_ws/build_isolated/test_diagnostic_aggregator/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/test_diagnostic_aggregator/test_results/test_diagnostic_aggregator/rostest-test_launch_test_match_no_analyze.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/diagnostics/test_diagnostic_aggregator --package=test_diagnostic_aggregator --results-filename test_launch_test_match_no_analyze.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/test_diagnostic_aggregator/test_results\" /home/koki/ros_catkin_ws/src/diagnostics/test_diagnostic_aggregator/test/launch/test_match_no_analyze.launch ")
set_tests_properties(_ctest_test_diagnostic_aggregator_rostest_test_launch_test_match_no_analyze.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/diagnostics/test_diagnostic_aggregator/CMakeLists.txt;25;add_rostest;/home/koki/ros_catkin_ws/src/diagnostics/test_diagnostic_aggregator/CMakeLists.txt;0;")
add_test(_ctest_test_diagnostic_aggregator_rostest_test_launch_test_match_then_analyze.launch "/home/koki/ros_catkin_ws/build_isolated/test_diagnostic_aggregator/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/test_diagnostic_aggregator/test_results/test_diagnostic_aggregator/rostest-test_launch_test_match_then_analyze.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/diagnostics/test_diagnostic_aggregator --package=test_diagnostic_aggregator --results-filename test_launch_test_match_then_analyze.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/test_diagnostic_aggregator/test_results\" /home/koki/ros_catkin_ws/src/diagnostics/test_diagnostic_aggregator/test/launch/test_match_then_analyze.launch ")
set_tests_properties(_ctest_test_diagnostic_aggregator_rostest_test_launch_test_match_then_analyze.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/diagnostics/test_diagnostic_aggregator/CMakeLists.txt;28;add_rostest;/home/koki/ros_catkin_ws/src/diagnostics/test_diagnostic_aggregator/CMakeLists.txt;0;")
add_test(_ctest_test_diagnostic_aggregator_rostest_test_launch_test_fail_init.launch "/home/koki/ros_catkin_ws/build_isolated/test_diagnostic_aggregator/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/test_diagnostic_aggregator/test_results/test_diagnostic_aggregator/rostest-test_launch_test_fail_init.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/diagnostics/test_diagnostic_aggregator --package=test_diagnostic_aggregator --results-filename test_launch_test_fail_init.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/test_diagnostic_aggregator/test_results\" /home/koki/ros_catkin_ws/src/diagnostics/test_diagnostic_aggregator/test/launch/test_fail_init.launch ")
set_tests_properties(_ctest_test_diagnostic_aggregator_rostest_test_launch_test_fail_init.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/diagnostics/test_diagnostic_aggregator/CMakeLists.txt;31;add_rostest;/home/koki/ros_catkin_ws/src/diagnostics/test_diagnostic_aggregator/CMakeLists.txt;0;")
add_test(_ctest_test_diagnostic_aggregator_rostest_test_launch_test_dual_analyzer_load.launch "/home/koki/ros_catkin_ws/build_isolated/test_diagnostic_aggregator/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/test_diagnostic_aggregator/test_results/test_diagnostic_aggregator/rostest-test_launch_test_dual_analyzer_load.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/diagnostics/test_diagnostic_aggregator --package=test_diagnostic_aggregator --results-filename test_launch_test_dual_analyzer_load.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/test_diagnostic_aggregator/test_results\" /home/koki/ros_catkin_ws/src/diagnostics/test_diagnostic_aggregator/test/launch/test_dual_analyzer_load.launch ")
set_tests_properties(_ctest_test_diagnostic_aggregator_rostest_test_launch_test_dual_analyzer_load.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/diagnostics/test_diagnostic_aggregator/CMakeLists.txt;34;add_rostest;/home/koki/ros_catkin_ws/src/diagnostics/test_diagnostic_aggregator/CMakeLists.txt;0;")
subdirs("gtest")
