set(_CATKIN_CURRENT_PACKAGE "dynamic_reconfigure")
set(dynamic_reconfigure_VERSION "1.7.1")
set(dynamic_reconfigure_MAINTAINER "Michael Carroll <michael@openrobotics.org>")
set(dynamic_reconfigure_PACKAGE_FORMAT "2")
set(dynamic_reconfigure_BUILD_DEPENDS "cpp_common" "message_generation" "roscpp_serialization" "rostest" "libboost-dev" "roscpp" "std_msgs")
set(dynamic_reconfigure_BUILD_EXPORT_DEPENDS "libboost-chrono-dev" "libboost-thread-dev" "libboost-dev" "roscpp" "std_msgs")
set(dynamic_reconfigure_BUILDTOOL_DEPENDS "catkin")
set(dynamic_reconfigure_BUILDTOOL_DEPENDS_catkin_VERSION_GTE "0.5.87")
set(dynamic_reconfigure_BUILDTOOL_EXPORT_DEPENDS )
set(dynamic_reconfigure_EXEC_DEPENDS "message_runtime" "roslib" "rospy" "rosservice" "libboost-dev" "roscpp" "std_msgs")
set(dynamic_reconfigure_RUN_DEPENDS "message_runtime" "roslib" "rospy" "rosservice" "libboost-dev" "roscpp" "std_msgs" "libboost-chrono-dev" "libboost-thread-dev")
set(dynamic_reconfigure_TEST_DEPENDS )
set(dynamic_reconfigure_DOC_DEPENDS )
set(dynamic_reconfigure_URL_WEBSITE "http://ros.org/wiki/dynamic_reconfigure")
set(dynamic_reconfigure_URL_BUGTRACKER "https://github.com/ros/dynamic_reconfigure/issues")
set(dynamic_reconfigure_URL_REPOSITORY "https://github.com/ros/dynamic_reconfigure")
set(dynamic_reconfigure_DEPRECATED "")