set(dynamic_reconfigure_SETUP_PY_SETUP_MODULE "setuptools")
set(dynamic_reconfigure_SETUP_PY_VERSION "1.7.1")
set(dynamic_reconfigure_SETUP_PY_SCRIPTS "")
set(dynamic_reconfigure_SETUP_PY_PACKAGES "dynamic_reconfigure")
set(dynamic_reconfigure_SETUP_PY_PACKAGE_DIRS "src/dynamic_reconfigure")
set(dynamic_reconfigure_SETUP_PY_MODULES "")
set(dynamic_reconfigure_SETUP_PY_MODULE_DIRS "")