set(rqt_gui_py_SETUP_PY_SETUP_MODULE "distutils.core")
set(rqt_gui_py_SETUP_PY_VERSION "0.5.2")
set(rqt_gui_py_SETUP_PY_SCRIPTS "")
set(rqt_gui_py_SETUP_PY_PACKAGES "rqt_gui_py")
set(rqt_gui_py_SETUP_PY_PACKAGE_DIRS "src/rqt_gui_py")
set(rqt_gui_py_SETUP_PY_MODULES "")
set(rqt_gui_py_SETUP_PY_MODULE_DIRS "")