# CMake generated Testfile for 
# Source directory: /home/koki/ros_catkin_ws/src/diagnostics/diagnostic_aggregator
# Build directory: /home/koki/ros_catkin_ws/build_isolated/diagnostic_aggregator
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_diagnostic_aggregator_rostest_test_launch_test_agg.launch "/home/koki/ros_catkin_ws/build_isolated/diagnostic_aggregator/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/diagnostic_aggregator/test_results/diagnostic_aggregator/rostest-test_launch_test_agg.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/diagnostics/diagnostic_aggregator --package=diagnostic_aggregator --results-filename test_launch_test_agg.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/diagnostic_aggregator/test_results\" /home/koki/ros_catkin_ws/src/diagnostics/diagnostic_aggregator/test/launch/test_agg.launch ")
set_tests_properties(_ctest_diagnostic_aggregator_rostest_test_launch_test_agg.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/diagnostics/diagnostic_aggregator/CMakeLists.txt;53;add_rostest;/home/koki/ros_catkin_ws/src/diagnostics/diagnostic_aggregator/CMakeLists.txt;0;")
add_test(_ctest_diagnostic_aggregator_rostest_test_launch_test_add_agg.launch "/home/koki/ros_catkin_ws/build_isolated/diagnostic_aggregator/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/diagnostic_aggregator/test_results/diagnostic_aggregator/rostest-test_launch_test_add_agg.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/diagnostics/diagnostic_aggregator --package=diagnostic_aggregator --results-filename test_launch_test_add_agg.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/diagnostic_aggregator/test_results\" /home/koki/ros_catkin_ws/src/diagnostics/diagnostic_aggregator/test/launch/test_add_agg.launch ")
set_tests_properties(_ctest_diagnostic_aggregator_rostest_test_launch_test_add_agg.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/diagnostics/diagnostic_aggregator/CMakeLists.txt;54;add_rostest;/home/koki/ros_catkin_ws/src/diagnostics/diagnostic_aggregator/CMakeLists.txt;0;")
add_test(_ctest_diagnostic_aggregator_rostest_test_launch_test_loader.launch "/home/koki/ros_catkin_ws/build_isolated/diagnostic_aggregator/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/diagnostic_aggregator/test_results/diagnostic_aggregator/rostest-test_launch_test_loader.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/diagnostics/diagnostic_aggregator --package=diagnostic_aggregator --results-filename test_launch_test_loader.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/diagnostic_aggregator/test_results\" /home/koki/ros_catkin_ws/src/diagnostics/diagnostic_aggregator/test/launch/test_loader.launch ")
set_tests_properties(_ctest_diagnostic_aggregator_rostest_test_launch_test_loader.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/diagnostics/diagnostic_aggregator/CMakeLists.txt;57;add_rostest;/home/koki/ros_catkin_ws/src/diagnostics/diagnostic_aggregator/CMakeLists.txt;0;")
add_test(_ctest_diagnostic_aggregator_rostest_test_launch_test_expected_stale.launch "/home/koki/ros_catkin_ws/build_isolated/diagnostic_aggregator/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/diagnostic_aggregator/test_results/diagnostic_aggregator/rostest-test_launch_test_expected_stale.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/diagnostics/diagnostic_aggregator --package=diagnostic_aggregator --results-filename test_launch_test_expected_stale.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/diagnostic_aggregator/test_results\" /home/koki/ros_catkin_ws/src/diagnostics/diagnostic_aggregator/test/launch/test_expected_stale.launch ")
set_tests_properties(_ctest_diagnostic_aggregator_rostest_test_launch_test_expected_stale.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/diagnostics/diagnostic_aggregator/CMakeLists.txt;58;add_rostest;/home/koki/ros_catkin_ws/src/diagnostics/diagnostic_aggregator/CMakeLists.txt;0;")
add_test(_ctest_diagnostic_aggregator_rostest_test_launch_test_multiple_match.launch "/home/koki/ros_catkin_ws/build_isolated/diagnostic_aggregator/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/diagnostic_aggregator/test_results/diagnostic_aggregator/rostest-test_launch_test_multiple_match.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/diagnostics/diagnostic_aggregator --package=diagnostic_aggregator --results-filename test_launch_test_multiple_match.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/diagnostic_aggregator/test_results\" /home/koki/ros_catkin_ws/src/diagnostics/diagnostic_aggregator/test/launch/test_multiple_match.launch ")
set_tests_properties(_ctest_diagnostic_aggregator_rostest_test_launch_test_multiple_match.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/diagnostics/diagnostic_aggregator/CMakeLists.txt;59;add_rostest;/home/koki/ros_catkin_ws/src/diagnostics/diagnostic_aggregator/CMakeLists.txt;0;")
subdirs("gtest")
