# CMake generated Testfile for 
# Source directory: /home/koki/ros_catkin_ws/src/kdl_parser/kdl_parser
# Build directory: /home/koki/ros_catkin_ws/build_isolated/kdl_parser
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_kdl_parser_rostest_test_test_kdl_parser.launch "/home/koki/ros_catkin_ws/build_isolated/kdl_parser/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/kdl_parser/test_results/kdl_parser/rostest-test_test_kdl_parser.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/kdl_parser/kdl_parser --package=kdl_parser --results-filename test_test_kdl_parser.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/kdl_parser/test_results\" /home/koki/ros_catkin_ws/src/kdl_parser/kdl_parser/test/test_kdl_parser.launch ")
set_tests_properties(_ctest_kdl_parser_rostest_test_test_kdl_parser.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;80;add_rostest;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;100;_add_rostest_google_test;/home/koki/ros_catkin_ws/src/kdl_parser/kdl_parser/CMakeLists.txt;43;add_rostest_gtest;/home/koki/ros_catkin_ws/src/kdl_parser/kdl_parser/CMakeLists.txt;0;")
add_test(_ctest_kdl_parser_rostest_test_test_inertia_rpy.launch "/home/koki/ros_catkin_ws/build_isolated/kdl_parser/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/kdl_parser/test_results/kdl_parser/rostest-test_test_inertia_rpy.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/kdl_parser/kdl_parser --package=kdl_parser --results-filename test_test_inertia_rpy.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/kdl_parser/test_results\" /home/koki/ros_catkin_ws/src/kdl_parser/kdl_parser/test/test_inertia_rpy.launch ")
set_tests_properties(_ctest_kdl_parser_rostest_test_test_inertia_rpy.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;80;add_rostest;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;100;_add_rostest_google_test;/home/koki/ros_catkin_ws/src/kdl_parser/kdl_parser/CMakeLists.txt;46;add_rostest_gtest;/home/koki/ros_catkin_ws/src/kdl_parser/kdl_parser/CMakeLists.txt;0;")
subdirs("gtest")
