# CMake generated Testfile for 
# Source directory: /home/koki/ros_catkin_ws/src/bond_core/test_bond
# Build directory: /home/koki/ros_catkin_ws/build_isolated/test_bond
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_test_bond_rostest_test_test_cpp.launch "/home/koki/ros_catkin_ws/build_isolated/test_bond/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/test_bond/test_results/test_bond/rostest-test_test_cpp.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/bond_core/test_bond --package=test_bond --results-filename test_test_cpp.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/test_bond/test_results\" /home/koki/ros_catkin_ws/src/bond_core/test_bond/test/test_cpp.launch ")
set_tests_properties(_ctest_test_bond_rostest_test_test_cpp.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/bond_core/test_bond/CMakeLists.txt;29;add_rostest;/home/koki/ros_catkin_ws/src/bond_core/test_bond/CMakeLists.txt;0;")
add_test(_ctest_test_bond_rostest_test_test_python.launch "/home/koki/ros_catkin_ws/build_isolated/test_bond/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/test_bond/test_results/test_bond/rostest-test_test_python.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/bond_core/test_bond --package=test_bond --results-filename test_test_python.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/test_bond/test_results\" /home/koki/ros_catkin_ws/src/bond_core/test_bond/test/test_python.launch ")
set_tests_properties(_ctest_test_bond_rostest_test_test_python.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/bond_core/test_bond/CMakeLists.txt;30;add_rostest;/home/koki/ros_catkin_ws/src/bond_core/test_bond/CMakeLists.txt;0;")
add_test(_ctest_test_bond_rostest_test_test_callbacks_cpp.launch "/home/koki/ros_catkin_ws/build_isolated/test_bond/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/test_bond/test_results/test_bond/rostest-test_test_callbacks_cpp.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/bond_core/test_bond --package=test_bond --results-filename test_test_callbacks_cpp.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/test_bond/test_results\" /home/koki/ros_catkin_ws/src/bond_core/test_bond/test/test_callbacks_cpp.launch ")
set_tests_properties(_ctest_test_bond_rostest_test_test_callbacks_cpp.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/bond_core/test_bond/CMakeLists.txt;39;add_rostest;/home/koki/ros_catkin_ws/src/bond_core/test_bond/CMakeLists.txt;0;")
add_test(_ctest_test_bond_rostest_test_test_callbacks_py.launch "/home/koki/ros_catkin_ws/build_isolated/test_bond/catkin_generated/env_cached.sh" "/usr/bin/python3" "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/run_tests.py" "/home/koki/ros_catkin_ws/build_isolated/test_bond/test_results/test_bond/rostest-test_test_callbacks_py.xml" "--return-code" "/usr/bin/python3 /home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/koki/ros_catkin_ws/src/bond_core/test_bond --package=test_bond --results-filename test_test_callbacks_py.xml --results-base-dir \"/home/koki/ros_catkin_ws/build_isolated/test_bond/test_results\" /home/koki/ros_catkin_ws/src/bond_core/test_bond/test/test_callbacks_py.launch ")
set_tests_properties(_ctest_test_bond_rostest_test_test_callbacks_py.launch PROPERTIES  _BACKTRACE_TRIPLES "/home/koki/ros_catkin_ws/install_isolated/share/catkin/cmake/test/tests.cmake;160;add_test;/home/koki/ros_catkin_ws/install_isolated/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/koki/ros_catkin_ws/src/bond_core/test_bond/CMakeLists.txt;40;add_rostest;/home/koki/ros_catkin_ws/src/bond_core/test_bond/CMakeLists.txt;0;")
subdirs("gtest")
