# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/home/koki/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/BatteryState.msg;/home/koki/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/CameraInfo.msg;/home/koki/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/ChannelFloat32.msg;/home/koki/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/CompressedImage.msg;/home/koki/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/FluidPressure.msg;/home/koki/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/Illuminance.msg;/home/koki/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/Image.msg;/home/koki/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/Imu.msg;/home/koki/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/JointState.msg;/home/koki/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/Joy.msg;/home/koki/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/JoyFeedback.msg;/home/koki/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/JoyFeedbackArray.msg;/home/koki/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/LaserEcho.msg;/home/koki/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/LaserScan.msg;/home/koki/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/MagneticField.msg;/home/koki/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/MultiDOFJointState.msg;/home/koki/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/MultiEchoLaserScan.msg;/home/koki/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/NavSatFix.msg;/home/koki/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/NavSatStatus.msg;/home/koki/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/PointCloud.msg;/home/koki/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/PointCloud2.msg;/home/koki/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/PointField.msg;/home/koki/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/Range.msg;/home/koki/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/RegionOfInterest.msg;/home/koki/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/RelativeHumidity.msg;/home/koki/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/Temperature.msg;/home/koki/ros_catkin_ws/src/common_msgs/sensor_msgs/msg/TimeReference.msg"
services_str = "/home/koki/ros_catkin_ws/src/common_msgs/sensor_msgs/srv/SetCameraInfo.srv"
pkg_name = "sensor_msgs"
dependencies_str = "geometry_msgs;std_msgs"
langs = "gencpp;geneus;genlisp;gennodejs;genpy"
dep_include_paths_str = "sensor_msgs;/home/koki/ros_catkin_ws/src/common_msgs/sensor_msgs/msg;geometry_msgs;/home/koki/ros_catkin_ws/install_isolated/share/geometry_msgs/cmake/../msg;std_msgs;/home/koki/ros_catkin_ws/install_isolated/share/std_msgs/cmake/../msg"
PYTHON_EXECUTABLE = "/usr/bin/python3"
package_has_static_sources = 'TRUE' == 'TRUE'
genmsg_check_deps_script = "/home/koki/ros_catkin_ws/install_isolated/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py"
